=== terry-norbraten/viskit/Schemas/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- CVS ID: $Id: assembly.dtd 2036 2008-08-21 18:01:17Z jmbailey $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:group name="DesignParameters">
    <xs:sequence>
      <xs:element ref="TerminalParameter"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="ValueRange" abstract="true">
    <xs:complexType>
      <xs:attribute name="lowValue"/>
      <xs:attribute name="highValue"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="Parameters">
    <xs:choice>
      <xs:element ref="MultiParameter"/>
      <xs:element ref="FactoryParameter"/>
      <xs:element ref="TerminalParameter"/>
    </xs:choice>
  </xs:group>
  <xs:element name="Statistics" abstract="true"/>
  <xs:element name="SimkitAssembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEntity"/>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="DesignParameters"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EventGraph"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListener"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEventListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Adapter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Output"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Verbose"/>
        <xs:element minOccurs="0" ref="Schedule"/>
        <xs:element minOccurs="0" ref="Experiment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="package" use="required"/>
      <xs:attribute name="extend" default="viskit.xsd.assembly.ViskitAssembly"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="url"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TerminalParameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="ValueRange"/>
      </xs:sequence>
      <xs:attribute name="name"/>
      <xs:attribute name="linkRef" type="xs:IDREF"/>
      <xs:attribute name="link" type="xs:ID"/>
      <xs:attribute name="value"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DoubleRange" substitutionGroup="ValueRange"/>
  <xs:element name="IntegerRange" substitutionGroup="ValueRange"/>
  <xs:element name="MultiParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FactoryParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="factory" use="required"/>
      <xs:attribute name="method" default="getInstance"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListener">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="mode" default="listener">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="replicationStat"/>
            <xs:enumeration value="designPointStat"/>
            <xs:enumeration value="listener"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="meanStatistics" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="countStatistics" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEventListenerConnection">
    <xs:complexType>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListenerConnection">
    <xs:complexType>
      <xs:attribute name="property"/>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Output">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Verbose">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:attribute name="stopTime" default="0.0"/>
      <xs:attribute name="verbose" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="numberReplications" default="1"/>
      <xs:attribute name="printReplicationReports" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="printSummaryReport" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="saveReplicationData" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Adapter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="eventHeard" use="required"/>
      <xs:attribute name="eventSent" use="required"/>
      <xs:attribute name="from" use="required" type="xs:IDREF"/>
      <xs:attribute name="to" use="required" type="xs:IDREF"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Log" type="xs:string"/>
  <xs:element name="Errors" type="xs:string"/>
  <xs:element name="PropertyChange">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="listenerName" use="required"/>
      <xs:attribute name="property"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:attribute name="name"/>
      <xs:attribute name="mean" default="0.0"/>
      <xs:attribute name="variance" default="0.0"/>
      <xs:attribute name="standardDeviation" default="0.0"/>
      <xs:attribute name="count" default="0"/>
      <xs:attribute name="minObs" default="0.0"/>
      <xs:attribute name="maxObs" default="0.0"/>
      <xs:attribute name="samplingType" default="TALLY">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="TALLY"/>
            <xs:enumeration value="TIME_VARYING"/>
            <xs:enumeration value="LINEAR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="IndexedSampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SampleStatistics"/>
      </xs:sequence>
      <xs:attribute name="name"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Results">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Log"/>
        <xs:element ref="PropertyChange"/>
        <xs:element ref="Errors"/>
      </xs:choice>
      <xs:attribute name="sample" use="required"/>
      <xs:attribute name="designPoint" use="required"/>
      <xs:attribute name="index"/>
      <xs:attribute name="job"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DesignPoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TerminalParameter"/>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Replication"/>
        <xs:element minOccurs="0" ref="Results"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Replication">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Script" type="xs:string"/>
  <xs:element name="Sample">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="DesignPoint"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Sample"/>
      </xs:sequence>
      <xs:attribute name="jobID"/>
      <xs:attribute name="type" default="latin-hypercube">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="latin-hypercube"/>
            <xs:enumeration value="full-factorial"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="replicationsPerDesignPoint" default="1"/>
      <xs:attribute name="totalSamples" default="1"/>
      <xs:attribute name="jitter" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="timeout" default="0"/>
      <xs:attribute name="debug" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="EventGraph">
    <xs:complexType mixed="true">
      <xs:attribute name="fileName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PasswordFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="User"/>
      </xs:sequence>
      <xs:attribute name="name" default="/tmp/passwd.xml"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="User">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="password" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/BehaviorLibraries/Theses/2007Seguin/Assemblies/MinefieldSearchAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="MinefieldSearchAssembly" package="seadiver" version="$Id$" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="Controls the movement and detection of all mines and seadivers, along with providing DIS capability." name="ScenarioManager" type="diskit.ScenarioManager">
        <TerminalParameter name="speedScale" type="double" value="1"/>
        <TerminalParameter name="clearOnReset" type="boolean" value="true"/>
        <TerminalParameter name="mulicastIPAddress" type="java.lang.String" value="239.1.2.3"/>
        <TerminalParameter name="port" type="int" value="6000"/>
        <TerminalParameter name="siteID" type="int" value="0"/>
        <TerminalParameter name="appID" type="int" value="1"/>
        <Coordinate x="90" y="330"/>
    </SimEntity>
    <SimEntity description="Defines the overall search area for operation by targets and subdivided search by seadivers.. Units are m/s." name="ZoneMap" type="seadiver.ZoneMap">
        <MultiParameter type="diskit.X3DCoordinate">
            <TerminalParameter name="X" type="double" value="0"/>
            <TerminalParameter name="Y (+Y is up)" type="double" value="0"/>
            <TerminalParameter name="Z" type="double" value="0"/>
        </MultiParameter>
        <TerminalParameter name="length" type="double" value="20000"/>
        <TerminalParameter name="width" type="double" value="20000"/>
        <TerminalParameter name="height" type="double" value="10"/>
        <Coordinate x="270" y="180"/>
    </SimEntity>
    <SimEntity description="LIst of identical seadiver robots that perform a cooperative search.  Units are m/s." name="SeaDivers" type="seadiver.SeaDiver">
        <TerminalParameter name="maximumSpeed" type="double" value="1.53"/>
        <TerminalParameter name="firstMoverID" type="int" value="100"/>
        <TerminalParameter name="numberDivers" type="int" value="100"/>
        <TerminalParameter name="sensorRange" type="double" value="100"/>
        <MultiParameter type="diskit.random.RandomVariateInstantiator">
            <MultiParameter type="diskit.random.AR1Variate"/>
            <MultiParameter type="diskit.random.BernoulliVariate"/>
            <MultiParameter type="diskit.random.BetaVariate"/>
            <MultiParameter type="diskit.random.BinomialVariate"/>
            <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
            <MultiParameter type="diskit.random.ExponentialVariate"/>
            <MultiParameter type="diskit.random.GammaVariate"/>
            <MultiParameter type="diskit.random.InverseGaussianVariate"/>
            <MultiParameter type="diskit.random.NormalVariate">
                <TerminalParameter name="Mean (-Infinity -&gt; +Infinity)" type="double" value="300"/>
                <TerminalParameter name="Standard Deviation (0.0 -&gt; +Infinity)" type="double" value="120"/>
            </MultiParameter>
            <MultiParameter type="diskit.random.PoissonVariate"/>
            <MultiParameter type="diskit.random.UniformVariate"/>
        </MultiParameter>
        <TerminalParameter name="inputFileTemplate" type="java.lang.String" value="G:/ThesisCode/MissionFiles/SeaDiverTemplate.xml"/>
        <TerminalParameter name="outputFileName" type="java.lang.String" value="G:/ThesisCode/MissionFiles/Diver.xml"/>
        <TerminalParameter name="operatingDepth" type="double" value="5"/>
        <Coordinate x="90" y="180"/>
    </SimEntity>
    <SimEntity description="List of identical, non-moving mine objects distributed through the operating area.  Units are m/s." name="MineField" type="seadiver.MineField">
        <TerminalParameter name="sensorRange" type="double" value="100"/>
        <TerminalParameter name="numberMines" type="int" value="200"/>
        <TerminalParameter name="firstMoverID" type="int" value="600"/>
        <TerminalParameter name="mineFieldWidth" type="double" value="20000"/>
        <TerminalParameter name="mineFieldLength" type="double" value="20000"/>
        <TerminalParameter name="mineFieldDepth" type="double" value="10"/>
        <MultiParameter type="diskit.random.RandomVariateInstantiator">
            <MultiParameter type="diskit.random.AR1Variate"/>
            <MultiParameter type="diskit.random.BernoulliVariate"/>
            <MultiParameter type="diskit.random.BetaVariate"/>
            <MultiParameter type="diskit.random.BinomialVariate"/>
            <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
            <MultiParameter type="diskit.random.ExponentialVariate"/>
            <MultiParameter type="diskit.random.GammaVariate"/>
            <MultiParameter type="diskit.random.InverseGaussianVariate"/>
            <MultiParameter type="diskit.random.NormalVariate"/>
            <MultiParameter type="diskit.random.PoissonVariate"/>
            <MultiParameter type="diskit.random.UniformVariate">
                <TerminalParameter name="low Value (-Infinity -&gt; +Infinity)" type="double" value="0"/>
                <TerminalParameter name="high Value (&gt;=lowValue -&gt; +Infinity)" type="double" value="20000"/>
            </MultiParameter>
        </MultiParameter>
        <MultiParameter type="diskit.random.RandomVariateInstantiator">
            <MultiParameter type="diskit.random.AR1Variate"/>
            <MultiParameter type="diskit.random.BernoulliVariate"/>
            <MultiParameter type="diskit.random.BetaVariate"/>
            <MultiParameter type="diskit.random.BinomialVariate"/>
            <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
            <MultiParameter type="diskit.random.ExponentialVariate"/>
            <MultiParameter type="diskit.random.GammaVariate"/>
            <MultiParameter type="diskit.random.InverseGaussianVariate"/>
            <MultiParameter type="diskit.random.NormalVariate"/>
            <MultiParameter type="diskit.random.PoissonVariate"/>
            <MultiParameter type="diskit.random.UniformVariate">
                <TerminalParameter name="low Value (-Infinity -&gt; +Infinity)" type="double" value="0"/>
                <TerminalParameter name="high Value (&gt;=lowValue -&gt; +Infinity)" type="double" value="20000"/>
            </MultiParameter>
        </MultiParameter>
        <MultiParameter type="diskit.random.RandomVariateInstantiator">
            <MultiParameter type="diskit.random.AR1Variate"/>
            <MultiParameter type="diskit.random.BernoulliVariate"/>
            <MultiParameter type="diskit.random.BetaVariate"/>
            <MultiParameter type="diskit.random.BinomialVariate"/>
            <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
            <MultiParameter type="diskit.random.ExponentialVariate"/>
            <MultiParameter type="diskit.random.GammaVariate"/>
            <MultiParameter type="diskit.random.InverseGaussianVariate"/>
            <MultiParameter type="diskit.random.NormalVariate"/>
            <MultiParameter type="diskit.random.PoissonVariate"/>
            <MultiParameter type="diskit.random.UniformVariate">
                <TerminalParameter name="low Value (-Infinity -&gt; +Infinity)" type="double" value="0"/>
                <TerminalParameter name="high Value (&gt;=lowValue -&gt; +Infinity)" type="double" value="1"/>
            </MultiParameter>
        </MultiParameter>
        <Coordinate x="270" y="330"/>
    </SimEntity>
    <PropertyChangeListener description="" mode="replicationStats" name="DetectionsByMine" type="simkit.stat.SimpleStatsTally">
        <TerminalParameter name="p[0] : " type="java.lang.String" value="numberOfDetectionsByMine"/>
        <Coordinate x="270" y="420"/>
    </PropertyChangeListener>
    <PropertyChangeListener description="Number of unique mines detected." mode="replicationStats" name="MineDetections" type="simkit.stat.SimpleStatsTally">
        <TerminalParameter name="p[0] : " type="java.lang.String" value="mineDetections"/>
        <Coordinate x="90" y="70"/>
    </PropertyChangeListener>
    <SimEventListenerConnection description="Scenario Manager is listening for register target and sensors." listener="ScenarioManager" source="SeaDivers"/>
    <SimEventListenerConnection description="ZoneMap listening for Create Map." listener="ZoneMap" source="SeaDivers"/>
    <SimEventListenerConnection description="Seadiver listening for Register Map." listener="SeaDivers" source="ZoneMap"/>
    <SimEventListenerConnection description="Scenario Manager is listening for register target and sensors." listener="ScenarioManager" source="MineField"/>
    <PropertyChangeListenerConnection description="Number of detections by mines." listener="DetectionsByMine" property="numberOfDetectionsByMine" source="MineField"/>
    <PropertyChangeListenerConnection description="Number of unique mines detected." listener="MineDetections" property="mineDetections" source="SeaDivers"/>
    <Schedule stopTime="100." verbose="false"/>
    <Experiment replicationsPerDesignPoint="1" timeout="5000" totalSamples="1"/>
</SimkitAssembly>

=== terry-norbraten/viskit/BehaviorLibraries/SavageTactics/Locations/IndianIsland.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="IndianIsland" package="atfp" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="" name="ScenarioManager" type="diskit.ScenarioManager">
        <TerminalParameter name="p[0] : " type="boolean" value="true"/>
        <TerminalParameter name="p[1] : " type="java.lang.String" value="239.255.5.8"/>
        <TerminalParameter name="p[2] : " type="int" value="62040"/>
        <TerminalParameter name="p[3] : " type="int" value="0"/>
        <TerminalParameter name="p[4] : " type="int" value="1"/>
        <Coordinate x="220" y="130"/>
    </SimEntity>
    <SimEntity description="Overall Area of ammo pier, includes the three access piers" name="AmmoPier" type="diskit.Pier">
        <MultiParameter type="diskit.Vec3d">
            <TerminalParameter name="p[0] : " type="double" value="-343.347"/>
            <TerminalParameter name="p[1] : " type="double" value="-1178.404"/>
            <TerminalParameter name="p[2] : " type="double" value="-47.074"/>
        </MultiParameter>
        <TerminalParameter name="length" type="double" value="360"/>
        <TerminalParameter name="width" type="double" value="20"/>
        <TerminalParameter name="height" type="double" value="3"/>
        <TerminalParameter name="rotation" type="double" value="-16.5"/>
        <Coordinate x="220" y="230"/>
    </SimEntity>
    <SimEntity description="" name="DISPinger" type="diskit.DISPinger">
        <TerminalParameter name="p[0] : " type="double" value=".2"/>
        <TerminalParameter name="p[1] : " type="long" value="200"/>
        <Coordinate x="220" y="20"/>
    </SimEntity>
    <SimEventListenerConnection listener="ScenarioManager" source="DISPinger"/>
    <Schedule stopTime="1000" verbose="false"/>
    <Experiment timeout="5000" totalSamples="1"/>
</SimkitAssembly>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/ArrayTesterAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="ArrayTestAssembly" version="1.0" package="examples" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="ArrayTester_3" type="examples.ArrayTester" description="">
        <MultiParameter type="int[]">
            <TerminalParameter name="" value="17" type="int"/>
            <TerminalParameter name="" value="52" type="int"/>
        </MultiParameter>
        <Coordinate x="160" y="60"/>
    </SimEntity>
    <PropertyChangeListener name="SimplePropertyDumper_4" type="simkit.util.SimplePropertyDumper" meanStatistics="false" countStatistics="true">
        <Coordinate x="160.0" y="190.0"/>
    </PropertyChangeListener>
    <PropertyChangeListenerConnection listener="SimplePropertyDumper_4" source="ArrayTester_3"/>
    <Output entity="ArrayTester_3"/>
    <Schedule stopTime="100." verbose="true"/>
    <Experiment replicationsPerDesignPoint="1" totalSamples="1" timeout="5000"/>
</SimkitAssembly>

=== terry-norbraten/viskit/examples/Assemblies/examples/ArrayTesterAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
    Document   : ArrayTesterAssembly.xml
    Created on : January 31, 2008, 1:57 PM
    Author     : $Id:$
    Description: Test Viskit's capability of creating primative array types
-->
<SimkitAssembly name="ArrayTestAssembly" package="examples" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="" name="ArrayTester_3" type="examples.ArrayTester">
        <MultiParameter type="int[]">
            <TerminalParameter name="" type="int" value="17"/>
            <TerminalParameter name="" type="int" value="52"/>
        </MultiParameter>
        <Coordinate x="160" y="60"/>
    </SimEntity>
    <PropertyChangeListener name="SimplePropertyDumper_4" type="simkit.util.SimplePropertyDumper">
        <Coordinate x="170" y="190"/>
    </PropertyChangeListener>
    <PropertyChangeListenerConnection listener="SimplePropertyDumper_4" source="ArrayTester_3"/>
    <Output entity="ArrayTester_3"/>
    <Schedule stopTime="100." verbose="true"/>
    <Experiment replicationsPerDesignPoint="1" timeout="5000" totalSamples="1"/>
</SimkitAssembly>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/TestServerGenericAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="TestServerGenericAssembly" version="$Id: TestServerGenericAssembly.xml 1590 2007-10-07 05:41:19Z tdnorbra $" package="examples" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="ServerGeneric_0" type="examples.ServerGeneric" description="">
        <TerminalParameter name="totalNumberServers" value="1" type="int"/>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Constant" type="java.lang.String"/>
            <TerminalParameter name="" value="1.1" type="double"/>
        </FactoryParameter>
        <Coordinate x="390.0" y="200.0"/>
    </SimEntity>
    <SimEntity name="ArrivalProcess_1" type="examples.ArrivalProcess" description="">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Exponential" type="java.lang.String"/>
            <TerminalParameter name="" value="1.2" type="double"/>
        </FactoryParameter>
        <Coordinate x="140.0" y="200.0"/>
    </SimEntity>
    <SimEntity name="EntityCreator_2" type="examples.EntityCreator" description="">
        <Coordinate x="260.0" y="200.0"/>
    </SimEntity>
    <SimEventListenerConnection listener="EntityCreator_2" source="ArrivalProcess_1"/>
    <Adapter name="adptr_3" eventHeard="EntityArrival" eventSent="Arrival" from="EntityCreator_2" to="ServerGeneric_0" description=""/>
    <Schedule stopTime="100." verbose="true"/>
    <Experiment replicationsPerDesignPoint="1" totalSamples="1" timeout="5000"/>
</SimkitAssembly>
