=== terry-norbraten/viskit/Schemas/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- CVS ID: $Id: assembly.dtd 2036 2008-08-21 18:01:17Z jmbailey $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:group name="DesignParameters">
    <xs:sequence>
      <xs:element ref="TerminalParameter"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="ValueRange" abstract="true">
    <xs:complexType>
      <xs:attribute name="lowValue"/>
      <xs:attribute name="highValue"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="Parameters">
    <xs:choice>
      <xs:element ref="MultiParameter"/>
      <xs:element ref="FactoryParameter"/>
      <xs:element ref="TerminalParameter"/>
    </xs:choice>
  </xs:group>
  <xs:element name="Statistics" abstract="true"/>
  <xs:element name="SimkitAssembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEntity"/>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="DesignParameters"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EventGraph"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListener"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEventListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Adapter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Output"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Verbose"/>
        <xs:element minOccurs="0" ref="Schedule"/>
        <xs:element minOccurs="0" ref="Experiment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="package" use="required"/>
      <xs:attribute name="extend" default="viskit.xsd.assembly.ViskitAssembly"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="url"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TerminalParameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="ValueRange"/>
      </xs:sequence>
      <xs:attribute name="name"/>
      <xs:attribute name="linkRef" type="xs:IDREF"/>
      <xs:attribute name="link" type="xs:ID"/>
      <xs:attribute name="value"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DoubleRange" substitutionGroup="ValueRange"/>
  <xs:element name="IntegerRange" substitutionGroup="ValueRange"/>
  <xs:element name="MultiParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FactoryParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="factory" use="required"/>
      <xs:attribute name="method" default="getInstance"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListener">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="mode" default="listener">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="replicationStat"/>
            <xs:enumeration value="designPointStat"/>
            <xs:enumeration value="listener"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="meanStatistics" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="countStatistics" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEventListenerConnection">
    <xs:complexType>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListenerConnection">
    <xs:complexType>
      <xs:attribute name="property"/>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Output">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Verbose">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:attribute name="stopTime" default="0.0"/>
      <xs:attribute name="verbose" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="numberReplications" default="1"/>
      <xs:attribute name="printReplicationReports" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="printSummaryReport" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="saveReplicationData" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Adapter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="eventHeard" use="required"/>
      <xs:attribute name="eventSent" use="required"/>
      <xs:attribute name="from" use="required" type="xs:IDREF"/>
      <xs:attribute name="to" use="required" type="xs:IDREF"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Log" type="xs:string"/>
  <xs:element name="Errors" type="xs:string"/>
  <xs:element name="PropertyChange">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="listenerName" use="required"/>
      <xs:attribute name="property"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:attribute name="name"/>
      <xs:attribute name="mean" default="0.0"/>
      <xs:attribute name="variance" default="0.0"/>
      <xs:attribute name="standardDeviation" default="0.0"/>
      <xs:attribute name="count" default="0"/>
      <xs:attribute name="minObs" default="0.0"/>
      <xs:attribute name="maxObs" default="0.0"/>
      <xs:attribute name="samplingType" default="TALLY">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="TALLY"/>
            <xs:enumeration value="TIME_VARYING"/>
            <xs:enumeration value="LINEAR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="IndexedSampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SampleStatistics"/>
      </xs:sequence>
      <xs:attribute name="name"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Results">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Log"/>
        <xs:element ref="PropertyChange"/>
        <xs:element ref="Errors"/>
      </xs:choice>
      <xs:attribute name="sample" use="required"/>
      <xs:attribute name="designPoint" use="required"/>
      <xs:attribute name="index"/>
      <xs:attribute name="job"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DesignPoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TerminalParameter"/>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Replication"/>
        <xs:element minOccurs="0" ref="Results"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Replication">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Script" type="xs:string"/>
  <xs:element name="Sample">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="DesignPoint"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Sample"/>
      </xs:sequence>
      <xs:attribute name="jobID"/>
      <xs:attribute name="type" default="latin-hypercube">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="latin-hypercube"/>
            <xs:enumeration value="full-factorial"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="replicationsPerDesignPoint" default="1"/>
      <xs:attribute name="totalSamples" default="1"/>
      <xs:attribute name="jitter" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="timeout" default="0"/>
      <xs:attribute name="debug" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="EventGraph">
    <xs:complexType mixed="true">
      <xs:attribute name="fileName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PasswordFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="User"/>
      </xs:sequence>
      <xs:attribute name="name" default="/tmp/passwd.xml"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="User">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="password" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/BehaviorLibraries/BasicExamples/ExampleAssemblies/ZoneMoverAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="ZoneMoverAssembly" package="ExampleAssemblies" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="" name="DISPinger" type="diskit.DISPinger">
        <TerminalParameter name="isActive" type="boolean" value="true"/>
        <TerminalParameter name="duration" type="double" value=".2"/>
        <TerminalParameter name="simTimePerMilSec" type="long" value="200"/>
        <Coordinate x="280" y="220"/>
    </SimEntity>
    <SimEntity description="" name="ScenarioManager" type="diskit.ScenarioManager">
        <TerminalParameter name="speedScale" type="double" value=".5"/>
        <TerminalParameter name="clearOnReset" type="boolean" value="true"/>
        <TerminalParameter name="mulicastIPAddress" type="java.lang.String" value="239.255.5.8"/>
        <TerminalParameter name="port" type="int" value="62040"/>
        <TerminalParameter name="siteID" type="int" value="0"/>
        <TerminalParameter name="appID" type="int" value="1"/>
        <Coordinate x="390" y="220"/>
    </SimEntity>
    <SimEntity description="" name="ZoneMover" type="examples.ZoneMover">
        <MultiParameter type="diskit.Vec3d">
            <TerminalParameter name="x" type="double" value="0"/>
            <TerminalParameter name="y" type="double" value="0"/>
            <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
        </MultiParameter>
        <TerminalParameter name="maximumSpeed" type="double" value="20"/>
        <TerminalParameter name="moverID" type="int" value="101"/>
        <MultiParameter type="diskit.ProbabilityZoneGeometry[]">
            <MultiParameter type="diskit.ProbabilityZoneGeometry">
                <TerminalParameter name="entityID" type="int" value="101"/>
                <TerminalParameter name="probability" type="double" value=".5"/>
                <MultiParameter type="diskit.X3DCoordinate">
                    <TerminalParameter name="X" type="double" value="-1337.14"/>
                    <TerminalParameter name="Y (+Y is up)" type="double" value="0"/>
                    <TerminalParameter name="Z" type="double" value="-1575.58"/>
                </MultiParameter>
                <TerminalParameter name="length" type="double" value="500"/>
                <TerminalParameter name="width" type="double" value="300"/>
                <TerminalParameter name="height" type="double" value="0"/>
                <MultiParameter type="diskit.Vec4d">
                    <TerminalParameter name="x" type="double" value="0"/>
                    <TerminalParameter name="y" type="double" value="0"/>
                    <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
                    <TerminalParameter name="radianRotation" type="double" value="0"/>
                </MultiParameter>
            </MultiParameter>
            <MultiParameter type="diskit.ProbabilityZoneGeometry">
                <TerminalParameter name="entityID" type="int" value="101"/>
                <TerminalParameter name="probability" type="double" value=".5"/>
                <MultiParameter type="diskit.X3DCoordinate">
                    <TerminalParameter name="X" type="double" value="-1152.41"/>
                    <TerminalParameter name="Y (+Y is up)" type="double" value="0"/>
                    <TerminalParameter name="Z" type="double" value="218.51"/>
                </MultiParameter>
                <TerminalParameter name="length" type="double" value="500"/>
                <TerminalParameter name="width" type="double" value="500"/>
                <TerminalParameter name="height" type="double" value="0"/>
                <MultiParameter type="diskit.Vec4d">
                    <TerminalParameter name="x" type="double" value="0"/>
                    <TerminalParameter name="y" type="double" value="0"/>
                    <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
                    <TerminalParameter name="radianRotation" type="double" value="0"/>
                </MultiParameter>
            </MultiParameter>
        </MultiParameter>
        <Coordinate x="480" y="220"/>
    </SimEntity>
    <SimEventListenerConnection listener="ScenarioManager" source="DISPinger"/>
    <SimEventListenerConnection listener="ScenarioManager" source="ZoneMover"/>
    <Schedule stopTime="1000" verbose="false"/>
    <Experiment replicationsPerDesignPoint="1" timeout="5000" totalSamples="1"/>
</SimkitAssembly>

=== terry-norbraten/viskit/examples/diskit/DISServer3DTestAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly package="diskit" version="1.0" name="DISServer3DTestAssembly" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="SimServer3DTest_0" type="diskit.SimServer3DTest">
        <TerminalParameter type="java.lang.String" value="239.0.0.5"/>
        <TerminalParameter type="int" value="1500"/>
        <TerminalParameter type="double" value=".001"/>
        <Coordinate y="189" x="285"/>
    </SimEntity>
    <SimEntity name="SimPinger_1" type="diskit.SimPinger">
        <TerminalParameter type="double" value="1.0"/>
        <TerminalParameter type="long" value="1000"/>
        <Coordinate y="81" x="133"/>
    </SimEntity>
    <PropertyChangeListener name="SimplePropertyDumper_1" type="simkit.util.SimplePropertyDumper">
        <Coordinate y="300" x="100"/>
    </PropertyChangeListener>
    <PropertyChangeListenerConnection property="" listener="SimplePropertyDumper_1" source="SimServer3DTest_0"/>
    <Output entity="SimServer3DTest_0"/>
    <Output entity="SimPinger_1"/>
    <Schedule verbose="false" stopTime="100."/>
</SimkitAssembly>

=== terry-norbraten/viskit/BehaviorLibraries/BasicExamples/ExampleAssemblies/RandomVariateDistributionExamples.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="RandomVariateDistributionExamples" package="ExampleAssemblies" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="" name="NormalDistPlot" type="RandomVariateGeneration.RandomVariatePlotter">
        <MultiParameter type="diskit.random.Histogram">
            <MultiParameter type="diskit.random.RandomVariateInstantiator">
                <MultiParameter type="diskit.random.AR1Variate"/>
                <MultiParameter type="diskit.random.BernoulliVariate"/>
                <MultiParameter type="diskit.random.BetaVariate"/>
                <MultiParameter type="diskit.random.BinomialVariate"/>
                <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
                <MultiParameter type="diskit.random.ExponentialVariate"/>
                <MultiParameter type="diskit.random.GammaVariate"/>
                <MultiParameter type="diskit.random.InverseGaussianVariate"/>
                <MultiParameter type="diskit.random.NormalVariate">
                    <TerminalParameter name="Mean (-Infitiny -&gt; +Infinity)" type="double" value="10"/>
                    <TerminalParameter name="Standard Deviation (0.0 -&gt; +Infinity)" type="double" value="3"/>
                </MultiParameter>
                <MultiParameter type="diskit.random.PoissonVariate"/>
                <MultiParameter type="diskit.random.UniformVariate"/>
            </MultiParameter>
            <TerminalParameter name="number of samples" type="int" value="1000"/>
            <TerminalParameter name="number of histogram bins" type="int" value="50"/>
            <TerminalParameter name="lowerBounds" type="double" value="0.0"/>
            <TerminalParameter name="upperBounds" type="double" value="30"/>
        </MultiParameter>
        <Coordinate x="80" y="130"/>
    </SimEntity>
    <SimEntity description="Example plot of an exponential Distribution" name="ExponenPlot" type="RandomVariateGeneration.RandomVariatePlotter">
        <MultiParameter type="diskit.random.Histogram">
            <MultiParameter type="diskit.random.RandomVariateInstantiator">
                <MultiParameter type="diskit.random.AR1Variate"/>
                <MultiParameter type="diskit.random.BernoulliVariate"/>
                <MultiParameter type="diskit.random.BetaVariate"/>
                <MultiParameter type="diskit.random.BinomialVariate"/>
                <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
                <MultiParameter type="diskit.random.ExponentialVariate">
                    <TerminalParameter name="mean (-Infinity -&gt; +Infinity)" type="double" value="10"/>
                </MultiParameter>
                <MultiParameter type="diskit.random.GammaVariate"/>
                <MultiParameter type="diskit.random.InverseGaussianVariate"/>
                <MultiParameter type="diskit.random.NormalVariate"/>
                <MultiParameter type="diskit.random.PoissonVariate"/>
                <MultiParameter type="diskit.random.UniformVariate"/>
            </MultiParameter>
            <TerminalParameter name="number of samples" type="int" value="1000"/>
            <TerminalParameter name="number of histogram bins" type="int" value="50"/>
            <TerminalParameter name="lowerBounds" type="double" value="0"/>
            <TerminalParameter name="upperBounds" type="double" value="30"/>
        </MultiParameter>
        <Coordinate x="80" y="70"/>
    </SimEntity>
    <SimEntity description="" name="PoissonPlot" type="RandomVariateGeneration.RandomVariatePlotter">
        <MultiParameter type="diskit.random.Histogram">
            <MultiParameter type="diskit.random.RandomVariateInstantiator">
                <MultiParameter type="diskit.random.AR1Variate"/>
                <MultiParameter type="diskit.random.BernoulliVariate"/>
                <MultiParameter type="diskit.random.BetaVariate"/>
                <MultiParameter type="diskit.random.BinomialVariate"/>
                <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
                <MultiParameter type="diskit.random.ExponentialVariate"/>
                <MultiParameter type="diskit.random.GammaVariate"/>
                <MultiParameter type="diskit.random.InverseGaussianVariate"/>
                <MultiParameter type="diskit.random.NormalVariate"/>
                <MultiParameter type="diskit.random.PoissonVariate">
                    <TerminalParameter name="mean (0 -&gt; +Infinity)" type="double" value="20"/>
                </MultiParameter>
                <MultiParameter type="diskit.random.UniformVariate"/>
            </MultiParameter>
            <TerminalParameter name="number of samples" type="int" value="1000"/>
            <TerminalParameter name="number of histogram bins" type="int" value="50"/>
            <TerminalParameter name="lowerBounds" type="double" value="0"/>
            <TerminalParameter name="upperBounds" type="double" value="30"/>
        </MultiParameter>
        <Coordinate x="80" y="190"/>
    </SimEntity>
    <SimEntity description="" name="BernoulliPlot" type="RandomVariateGeneration.RandomVariatePlotter">
        <MultiParameter type="diskit.random.Histogram">
            <MultiParameter type="diskit.random.RandomVariateInstantiator">
                <MultiParameter type="diskit.random.AR1Variate"/>
                <MultiParameter type="diskit.random.BernoulliVariate">
                    <TerminalParameter name="P{X=1} (0.0 -&gt; 1.0)" type="double" value=".8"/>
                </MultiParameter>
                <MultiParameter type="diskit.random.BetaVariate"/>
                <MultiParameter type="diskit.random.BinomialVariate"/>
                <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
                <MultiParameter type="diskit.random.ExponentialVariate"/>
                <MultiParameter type="diskit.random.GammaVariate"/>
                <MultiParameter type="diskit.random.InverseGaussianVariate"/>
                <MultiParameter type="diskit.random.NormalVariate"/>
                <MultiParameter type="diskit.random.PoissonVariate"/>
                <MultiParameter type="diskit.random.UniformVariate"/>
            </MultiParameter>
            <TerminalParameter name="number of samples" type="int" value="1000"/>
            <TerminalParameter name="number of histogram bins" type="int" value="50"/>
            <TerminalParameter name="lowerBounds" type="double" value="0"/>
            <TerminalParameter name="upperBounds" type="double" value="5"/>
        </MultiParameter>
        <Coordinate x="160" y="70"/>
    </SimEntity>
    <SimEntity description="" name="GammaPlot" type="RandomVariateGeneration.RandomVariatePlotter">
        <MultiParameter type="diskit.random.Histogram">
            <MultiParameter type="diskit.random.RandomVariateInstantiator">
                <MultiParameter type="diskit.random.AR1Variate"/>
                <MultiParameter type="diskit.random.BernoulliVariate"/>
                <MultiParameter type="diskit.random.BetaVariate"/>
                <MultiParameter type="diskit.random.BinomialVariate"/>
                <MultiParameter type="diskit.random.DiscreteUniformVariate"/>
                <MultiParameter type="diskit.random.ExponentialVariate"/>
                <MultiParameter type="diskit.random.GammaVariate">
                    <TerminalParameter name="alpha (0 -&gt; +Infinity)" type="double" value="2"/>
                    <TerminalParameter name="beta (0 -&gt; +Infinity)" type="double" value="5"/>
                </MultiParameter>
                <MultiParameter type="diskit.random.InverseGaussianVariate"/>
                <MultiParameter type="diskit.random.NormalVariate"/>
                <MultiParameter type="diskit.random.PoissonVariate"/>
                <MultiParameter type="diskit.random.UniformVariate"/>
            </MultiParameter>
            <TerminalParameter name="number of samples" type="int" value="1000"/>
            <TerminalParameter name="number of histogram bins" type="int" value="50"/>
            <TerminalParameter name="lowerBounds" type="double" value="0.0"/>
            <TerminalParameter name="upperBounds" type="double" value="30"/>
        </MultiParameter>
        <Coordinate x="160" y="130"/>
    </SimEntity>
    <Schedule stopTime="100." verbose="false"/>
    <Experiment replicationsPerDesignPoint="1" timeout="5000" totalSamples="1"/>
</SimkitAssembly>
