=== terry-norbraten/viskit/Schemas/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- CVS ID: $Id: assembly.dtd 2036 2008-08-21 18:01:17Z jmbailey $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:group name="DesignParameters">
    <xs:sequence>
      <xs:element ref="TerminalParameter"/>
    </xs:sequence>
  </xs:group>
  <xs:element name="ValueRange" abstract="true">
    <xs:complexType>
      <xs:attribute name="lowValue"/>
      <xs:attribute name="highValue"/>
    </xs:complexType>
  </xs:element>
  <xs:group name="Parameters">
    <xs:choice>
      <xs:element ref="MultiParameter"/>
      <xs:element ref="FactoryParameter"/>
      <xs:element ref="TerminalParameter"/>
    </xs:choice>
  </xs:group>
  <xs:element name="Statistics" abstract="true"/>
  <xs:element name="SimkitAssembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEntity"/>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="DesignParameters"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EventGraph"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListener"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SimEventListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="PropertyChangeListenerConnection"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Adapter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Output"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Verbose"/>
        <xs:element minOccurs="0" ref="Schedule"/>
        <xs:element minOccurs="0" ref="Experiment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="package" use="required"/>
      <xs:attribute name="extend" default="viskit.xsd.assembly.ViskitAssembly"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="url"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="TerminalParameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="ValueRange"/>
      </xs:sequence>
      <xs:attribute name="name"/>
      <xs:attribute name="linkRef" type="xs:IDREF"/>
      <xs:attribute name="link" type="xs:ID"/>
      <xs:attribute name="value"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DoubleRange" substitutionGroup="ValueRange"/>
  <xs:element name="IntegerRange" substitutionGroup="ValueRange"/>
  <xs:element name="MultiParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FactoryParameter">
    <xs:complexType>
      <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
      <xs:attribute name="name"/>
      <xs:attribute name="factory" use="required"/>
      <xs:attribute name="method" default="getInstance"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListener">
    <xs:complexType>
      <xs:sequence>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="Parameters"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="mode" default="listener">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="replicationStat"/>
            <xs:enumeration value="designPointStat"/>
            <xs:enumeration value="listener"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="meanStatistics" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="countStatistics" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SimEventListenerConnection">
    <xs:complexType>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyChangeListenerConnection">
    <xs:complexType>
      <xs:attribute name="property"/>
      <xs:attribute name="listener" use="required"/>
      <xs:attribute name="source" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Output">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Verbose">
    <xs:complexType>
      <xs:attribute name="entity" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:attribute name="stopTime" default="0.0"/>
      <xs:attribute name="verbose" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="numberReplications" default="1"/>
      <xs:attribute name="printReplicationReports" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="printSummaryReport" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="saveReplicationData" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Adapter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="eventHeard" use="required"/>
      <xs:attribute name="eventSent" use="required"/>
      <xs:attribute name="from" use="required" type="xs:IDREF"/>
      <xs:attribute name="to" use="required" type="xs:IDREF"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Log" type="xs:string"/>
  <xs:element name="Errors" type="xs:string"/>
  <xs:element name="PropertyChange">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="listenerName" use="required"/>
      <xs:attribute name="property"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:attribute name="name"/>
      <xs:attribute name="mean" default="0.0"/>
      <xs:attribute name="variance" default="0.0"/>
      <xs:attribute name="standardDeviation" default="0.0"/>
      <xs:attribute name="count" default="0"/>
      <xs:attribute name="minObs" default="0.0"/>
      <xs:attribute name="maxObs" default="0.0"/>
      <xs:attribute name="samplingType" default="TALLY">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="TALLY"/>
            <xs:enumeration value="TIME_VARYING"/>
            <xs:enumeration value="LINEAR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="IndexedSampleStatistics" substitutionGroup="Statistics">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="SampleStatistics"/>
      </xs:sequence>
      <xs:attribute name="name"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Results">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Log"/>
        <xs:element ref="PropertyChange"/>
        <xs:element ref="Errors"/>
      </xs:choice>
      <xs:attribute name="sample" use="required"/>
      <xs:attribute name="designPoint" use="required"/>
      <xs:attribute name="index"/>
      <xs:attribute name="job"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DesignPoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="TerminalParameter"/>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Replication"/>
        <xs:element minOccurs="0" ref="Results"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Replication">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Statistics"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Script" type="xs:string"/>
  <xs:element name="Sample">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="DesignPoint"/>
      </xs:sequence>
      <xs:attribute name="index"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Script"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Sample"/>
      </xs:sequence>
      <xs:attribute name="jobID"/>
      <xs:attribute name="type" default="latin-hypercube">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="latin-hypercube"/>
            <xs:enumeration value="full-factorial"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="replicationsPerDesignPoint" default="1"/>
      <xs:attribute name="totalSamples" default="1"/>
      <xs:attribute name="jitter" default="true">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="timeout" default="0"/>
      <xs:attribute name="debug" default="false">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="EventGraph">
    <xs:complexType mixed="true">
      <xs:attribute name="fileName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PasswordFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="User"/>
      </xs:sequence>
      <xs:attribute name="name" default="/tmp/passwd.xml"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="User">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="password" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/ServerWithRenegesAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="ServerWithRenegesAssembly" version="1.0" package="examples" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <TerminalParameter name="arrivalProcess_1_1_1" link="arrivalProcess_1_1_1" value="Exponential" type="java.lang.String">
        <DoubleRange lowValue="Exponential" highValue="Exponential"/>
    </TerminalParameter>
    <TerminalParameter name="arrivalProcess_1_2_1_1_1" link="arrivalProcess_1_2_1_1_1" value="1.5" type="double">
        <DoubleRange lowValue="1.5" highValue="1.5"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_1_1" link="serverWithReneges_1_1" value="2" type="int">
        <DoubleRange lowValue="2" highValue="2"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_2_1_1" link="serverWithReneges_2_1_1" value="Gamma" type="java.lang.String">
        <DoubleRange lowValue="Gamma" highValue="Gamma"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_2_2_1_1" link="serverWithReneges_2_2_1_1" value="new Double(2.5)" type="java.lang.Object">
        <DoubleRange lowValue="new Double(2.5)" highValue="new Double(2.5)"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_2_2_2_1_1" link="serverWithReneges_2_2_2_1_1" value="1.2" type="double">
        <DoubleRange lowValue="1.2" highValue="1.2"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_3_1_1" link="serverWithReneges_3_1_1" value="Uniform" type="java.lang.String">
        <DoubleRange lowValue="Uniform" highValue="Uniform"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_3_2_1_1" link="serverWithReneges_3_2_1_1" value="new Integer(4)" type="java.lang.Object">
        <DoubleRange lowValue="new Integer(4)" highValue="new Integer(4)"/>
    </TerminalParameter>
    <TerminalParameter name="serverWithReneges_3_2_2_1" link="serverWithReneges_3_2_2_1" value="new Integer(6)" type="java.lang.Object">
        <DoubleRange lowValue="new Integer(6)" highValue="new Integer(6)"/>
    </TerminalParameter>
    <SimEntity name="arrivalProcess" type="examples.ArrivalProcess">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="arrivalProcess_1_1_1" linkRef="arrivalProcess_1_1_1" value="Exponential" type="java.lang.String"/>
            <MultiParameter type="java.lang.Object[]">
                <MultiParameter type="java.lang.Double">
                    <TerminalParameter name="arrivalProcess_1_2_1_1_1" linkRef="arrivalProcess_1_2_1_1_1" value="1.5" type="double"/>
                </MultiParameter>
            </MultiParameter>
        </FactoryParameter>
        <Coordinate x="40" y="140"/>
    </SimEntity>
    <SimEntity name="creator" type="examples.Creator">
        <Coordinate x="190" y="140"/>
    </SimEntity>
    <SimEntity name="serverWithReneges" type="examples.ServerWithReneges">
        <TerminalParameter name="serverWithReneges_1_1" linkRef="serverWithReneges_1_1" value="2" type="int"/>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="serverWithReneges_2_1_1" linkRef="serverWithReneges_2_1_1" value="Gamma" type="java.lang.String"/>
            <MultiParameter type="java.lang.Object[]">
                <TerminalParameter name="serverWithReneges_2_2_1_1" linkRef="serverWithReneges_2_2_1_1" value="new Double(2.5)" type="java.lang.Object"/>
                <MultiParameter type="java.lang.Double">
                    <TerminalParameter name="serverWithReneges_2_2_2_1_1" linkRef="serverWithReneges_2_2_2_1_1" value="1.2" type="double"/>
                </MultiParameter>
            </MultiParameter>
        </FactoryParameter>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="serverWithReneges_3_1_1" linkRef="serverWithReneges_3_1_1" value="Uniform" type="java.lang.String"/>
            <MultiParameter type="java.lang.Object[]">
                <TerminalParameter name="serverWithReneges_3_2_1_1" linkRef="serverWithReneges_3_2_1_1" value="new Integer(4)" type="java.lang.Object"/>
                <TerminalParameter name="serverWithReneges_3_2_2_1" linkRef="serverWithReneges_3_2_2_1" value="new Integer(6)" type="java.lang.Object"/>
            </MultiParameter>
        </FactoryParameter>
        <Coordinate x="350" y="140"/>
    </SimEntity>
    <PropertyChangeListener name="numberInQueueStat" type="simkit.stat.CollectionSizeTimeVaryingStats" mode="replicationStat">
        <TerminalParameter value="queue" type="java.lang.String"/>
        <Coordinate x="230" y="260"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberAvailableServersStat" type="simkit.stat.SimpleStatsTally" mode="replicationStat">
        <TerminalParameter value="numberAvailableServers" type="java.lang.String"/>
        <Coordinate x="320" y="260"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberServedStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat">
        <TerminalParameter value="numberServed" type="java.lang.String"/>
        <Coordinate x="410" y="260"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberRenegesStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat">
        <TerminalParameter value="numberReneges" type="java.lang.String"/>
        <Coordinate x="510" y="260"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberArrivalsStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat">
        <TerminalParameter value="numberArrivals" type="java.lang.String"/>
        <Coordinate x="40" y="260"/>
    </PropertyChangeListener>
    <SimEventListenerConnection listener="creator" source="arrivalProcess"/>
    <PropertyChangeListenerConnection property="queue" listener="numberInQueueStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberAvailableServers" listener="numberAvailableServersStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberServed" listener="numberServedStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberReneges" listener="numberRenegesStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberArrivals" listener="numberArrivalsStat" source="arrivalProcess"/>
    <Adapter name="adptr_3" eventHeard="CustomerArrival" eventSent="Arrival" from="creator" to="serverWithReneges"/>
    <Output entity="creator"/>
    <Output entity="arrivalProcess"/>
    <Output entity="serverWithReneges"/>
    <Schedule stopTime="10000.0" verbose="true"/>
    <Experiment replicationsPerDesignPoint="1" totalSamples="1" timeout="5000"/>
</SimkitAssembly>

=== terry-norbraten/viskit/BehaviorLibraries/BasicExamples/ExampleAssemblies/PathMoverAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="PathMoverAssembly" package="ExampleAssemblies" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity description="" name="DISPinger" type="diskit.DISPinger">
        <TerminalParameter name="isActive" type="boolean" value="true"/>
        <TerminalParameter name="duration" type="double" value=".2"/>
        <TerminalParameter name="simTimePerMilSec" type="long" value="200"/>
        <Coordinate x="280" y="220"/>
    </SimEntity>
    <SimEntity description="" name="ScenarioManager" type="diskit.ScenarioManager">
        <TerminalParameter name="speedScale" type="double" value=".5"/>
        <TerminalParameter name="clearOnReset" type="boolean" value="true"/>
        <TerminalParameter name="mulicastIPAddress" type="java.lang.String" value="239.255.5.8"/>
        <TerminalParameter name="port" type="int" value="62040"/>
        <TerminalParameter name="siteID" type="int" value="0"/>
        <TerminalParameter name="appID" type="int" value="1"/>
        <Coordinate x="390" y="220"/>
    </SimEntity>
    <SimEntity description="" name="PathMover" type="examples.PathMover">
        <MultiParameter type="diskit.Vec3d">
            <TerminalParameter name="x" type="double" value="-1410"/>
            <TerminalParameter name="y" type="double" value="-746"/>
            <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
        </MultiParameter>
        <TerminalParameter name="maximumSpeed" type="double" value="20"/>
        <TerminalParameter name="moverID" type="int" value="101"/>
        <MultiParameter type="diskit.Vec3d[]">
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1670.41"/>
                <TerminalParameter name="y" type="double" value="-1438.68"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1715.83"/>
                <TerminalParameter name="y" type="double" value="-1170.80"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1614.89"/>
                <TerminalParameter name="y" type="double" value="-772.124"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1206.12"/>
                <TerminalParameter name="y" type="double" value="-353.26"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-928.567"/>
                <TerminalParameter name="y" type="double" value="-338.12"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-746.891"/>
                <TerminalParameter name="y" type="double" value="-524.843"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1054.73"/>
                <TerminalParameter name="y" type="double" value="-782.217"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1095.104"/>
                <TerminalParameter name="y" type="double" value="-1276.78"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
            <MultiParameter type="diskit.Vec3d">
                <TerminalParameter name="x" type="double" value="-1670.41"/>
                <TerminalParameter name="y" type="double" value="-1438.68"/>
                <TerminalParameter name="z (-Z is up)" type="double" value="0"/>
            </MultiParameter>
        </MultiParameter>
        <Coordinate x="440" y="120"/>
    </SimEntity>
    <SimEventListenerConnection listener="ScenarioManager" source="DISPinger"/>
    <SimEventListenerConnection listener="ScenarioManager" source="PathMover"/>
    <Schedule stopTime="1000" verbose="false"/>
    <Experiment replicationsPerDesignPoint="1" timeout="5000" totalSamples="1"/>
</SimkitAssembly>
