=== terry-norbraten/viskit/Schemas/simkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Event"/>
        <xs:element minOccurs="0" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="package" default="examples"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="author"/>
      <xs:attribute name="extend" default="SimEntityBase"/>
      <xs:attribute name="implement"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Comment" type="xs:string"/>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StateVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Event">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Argument"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LocalVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateTransition"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Schedule"/>
          <xs:element ref="Cancel"/>
        </xs:choice>
        <xs:element minOccurs="0" ref="Code"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Code" type="xs:string"/>
  <xs:element name="Argument">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocalVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="value"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Operation">
    <xs:complexType>
      <xs:attribute name="method" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Assignment">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <!-- bux fix 1183 -->
  <xs:element name="StateTransition">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="Assignment"/>
          <xs:element ref="Operation"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="state" use="required" type="xs:IDREF"/>
      <xs:attribute name="index"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EdgeParameter">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="delay" default="0.0"/>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="priority" default="DEFAULT">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="HIGHEST"/>
            <xs:enumeration value="HIGHER"/>
            <xs:enumeration value="HIGH"/>
            <xs:enumeration value="DEFAULT"/>
            <xs:enumeration value="LOW"/>
            <xs:enumeration value="LOWER"/>
            <xs:enumeration value="LOWEST"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cancel">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/examples/EntityCreator.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="ahbuss" extend="SimEntityBase" name="EntityCreator" package="examples" version="$Id: EntityCreator.xml 1590 2007-10-07 05:41:19Z tdnorbra $" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Event name="Arrival">
        <Comment/>
        <Schedule condition="true" delay="0.0" event="EntityArrival" priority="0.0">
            <Comment/>
            <EdgeParameter value="new simkit.Entity()"/>
        </Schedule>
        <Code/>
        <Coordinate x="20" y="190"/>
    </Event>
    <Event name="EntityArrival">
        <Comment/>
        <Argument name="customer" type="simkit.Entity"/>
        <Code/>
        <Coordinate x="120" y="190"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/examples/OA3302/ServerGeneric.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="ahbuss" extend="SimEntityBase" name="ServerGeneric" package="test" version="$Id$" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="totalNumberServers" type="int">
        <Comment/>
    </Parameter>
    <Parameter name="serviceTimeGenerator" type="simkit.random.RandomVariate">
        <Comment/>
    </Parameter>
    <StateVariable name="numberAvailableServers" type="int">
        <Comment/>
    </StateVariable>
    <StateVariable name="queue" type="java.util.LinkedList&lt;simkit.Entity&gt;">
        <Comment/>
    </StateVariable>
    <StateVariable name="delayInQueue" type="double">
        <Comment/>
    </StateVariable>
    <StateVariable name="timeInSystem" type="double">
        <Comment/>
    </StateVariable>
    <Event name="Run">
        <Comment/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="totalNumberServers"/>
        </StateTransition>
        <StateTransition state="queue">
            <Assignment value="new java.util.LinkedList&lt;simkit.Entity&gt;()"/>
        </StateTransition>
        <Code/>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="Arrival">
        <Comment/>
        <Argument name="customer" type="simkit.Entity"/>
        <StateTransition state="queue">
            <Operation method="add(customer)"/>
        </StateTransition>
        <Schedule condition="numberAvailableServers &gt; 0" delay="0.0" event="StartService" priority="10.0">
            <Comment/>
        </Schedule>
        <Code>customer.stampTime();</Code>
        <Coordinate x="30" y="170"/>
    </Event>
    <Event name="StartService">
        <Comment/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <StateTransition state="queue">
            <Operation method="removeFirst()"/>
        </StateTransition>
        <StateTransition state="delayInQueue">
            <Assignment value="customer.getElapsedTime()"/>
        </StateTransition>
        <Schedule condition="true" delay="serviceTimeGenerator.generate()" event="EndService" priority="0.0">
            <Comment/>
            <EdgeParameter value="customer"/>
        </Schedule>
        <Code>Entity customer = queue.getFirst();</Code>
        <Coordinate x="170" y="160"/>
    </Event>
    <Event name="EndService">
        <Comment/>
        <Argument name="customer" type="simkit.Entity"/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers + 1"/>
        </StateTransition>
        <StateTransition state="timeInSystem">
            <Assignment value="customer.getElapsedTime()"/>
        </StateTransition>
        <Schedule condition="queue.size() &gt; 0" delay="0.0" event="StartService" priority="10.0">
            <Comment/>
        </Schedule>
        <Code/>
        <Coordinate x="290" y="160"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/SavageTactics/Sensors/MotionSensor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="Rick Goldberg" extend="diskit.SphereCutterSensor" name="MotionSensor" package="Sensors" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>Sporadically creates false detections. Set mean time between failures in parameters.</Comment>
    <Parameter name="mover" type="diskit.Mover3D">
        <Comment/>
    </Parameter>
    <Parameter name="maxRange" type="double">
        <Comment/>
    </Parameter>
    <Parameter name="MTBF" type="double">
        <Comment>mean time between failures</Comment>
    </Parameter>
    <Parameter name="MTBFStandarDeviation" type="double">
        <Comment>standard deviation of failures</Comment>
    </Parameter>
    <StateVariable name="MTBFVariate" type="simkit.random.RandomVariate">
        <Comment>random variate for MTBF</Comment>
    </StateVariable>
    <StateVariable name="falsePositiveCount" type="int">
        <Comment>keeps a tally</Comment>
    </StateVariable>
    <StateVariable name="self" type="Sensors.MotionSensor">
        <Comment>reference to this</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment/>
        <StateTransition state="MTBFVariate">
            <Assignment value="simkit.random.RandomVariateFactory.getInstance(&quot;NormalVariate&quot;,MTBF,MTBFStandarDeviation)"/>
        </StateTransition>
        <StateTransition state="falsePositiveCount">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="self">
            <Assignment value="this"/>
        </StateTransition>
        <StateTransition state="self">
            <Operation method="setMover((diskit.Mover3D)getSimEventListeners()[0])"/>
        </StateTransition>
        <Schedule condition="true" delay="java.lang.Math.max(0.0,MTBFVariate.generate())" event="FalsePositive" priority="0.0">
            <Comment/>
        </Schedule>
        <Code/>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="Detection">
        <Comment/>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Argument name="contact" type="diskit.Mover3D">
            <Comment>either the contact or a phantom</Comment>
        </Argument>
        <Code/>
        <Coordinate x="190" y="150"/>
    </Event>
    <Event name="FalsePositive">
        <Comment/>
        <StateTransition state="falsePositiveCount">
            <Assignment value="falsePositiveCount+1"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="Detection" priority="0.0">
            <Comment/>
            <EdgeParameter value="this"/>
            <EdgeParameter value="this.getMover()"/>
        </Schedule>
        <Schedule condition="true" delay="java.lang.Math.max(0.0,MTBFVariate.generate())" event="FalsePositive" priority="0.0">
            <Comment/>
        </Schedule>
        <Code/>
        <Coordinate x="30" y="150"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/examples/SimpleServer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="SimpleServer" version="0.1" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter type="simkit.random.RandomVariate" name="serviceTime"/>
    <Parameter type="int" name="totalNumberServers"/>
    <StateVariable name="numberInQueue" type="int"/>
    <StateVariable name="numberAvailableServers" type="int"/>
    <Event name="Run">
        <StateTransition state="numberInQueue">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="totalNumberServers"/>
        </StateTransition>
        <Coordinate y="0" x="10"/>
    </Event>
    <Event name="Arrival">
        <StateTransition state="numberInQueue">
            <Assignment value="numberInQueue + 1"/>
        </StateTransition>
        <Schedule condition="numberAvailableServers &gt; 0" priority="1.0" delay="0.0" event="StartService"/>
        <Coordinate y="100" x="10"/>
    </Event>
    <Event name="StartService">
        <StateTransition state="numberInQueue">
            <Assignment value="numberInQueue - 1"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <Schedule delay="serviceTime.generate()" event="EndService"/>
        <Coordinate y="100" x="150"/>
    </Event>
    <Event name="EndService">
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers + 1"/>
        </StateTransition>
        <Schedule condition="numberInQueue &gt; 0" priority="1.0" delay="0.0" event="StartService"/>
        <Coordinate y="100" x="320"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/Creator.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="Creator" package="examples" version="1.0" author="ahbuss" extend="SimEntityBase" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <StateVariable name="nextID" type="int">
        <Comment></Comment>
    </StateVariable>
    <Event name="Arrival">
        <Comment></Comment>
        <StateTransition state="nextID">
            <Assignment value="nextID+1"/>
        </StateTransition>
        <Schedule delay="0.0" event="CustomerArrival" condition="true" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="new Integer(nextID)"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="30.0" y="120.0"/>
    </Event>
    <Event name="CustomerArrival">
        <Comment></Comment>
        <Argument name="customer" type="Integer"/>
        <Code></Code>
        <Coordinate x="190.0" y="120.0"/>
    </Event>
    <Event name="Run">
        <Comment></Comment>
        <StateTransition state="nextID">
            <Assignment value="0"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="30.0" y="10.0"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ArrayTester.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ArrayTester" package="examples" version="1.0" author="Terry D. Norbraten" extend="SimEntityBase" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>Test Viskit's capability to create primative type arrays</Comment>
    <Parameter name="param_0" type="int[]">
        <Comment></Comment>
    </Parameter>
    <StateVariable name="state_0" type="int[param_0.length]">
        <Comment></Comment>
    </StateVariable>
    <Event name="Run">
        <Schedule delay="0.0" event="Init" condition="true" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="0"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="30.0" y="30.0"/>
    </Event>
    <Event name="Init">
        <Comment></Comment>
        <Argument name="i" type="int"/>
        <StateTransition state="state_0" index="i">
            <Assignment value="param_0[i]"/>
        </StateTransition>
        <Schedule delay="0.0" event="Init" condition="i &lt; (param_0.length - 1)" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="i + 1"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="180.0" y="30.0"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/Theses/2007Seguin/EventGraphs/MineField.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="jmseguin" extend="SimEntityBase" name="MineField" package="seadiver" version="$Id$" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="sensorRange" type="double">
        <Comment>Range of mine's sensor.</Comment>
    </Parameter>
    <Parameter name="numberMines" type="int">
        <Comment>Number of mines in the field.</Comment>
    </Parameter>
    <Parameter name="firstMoverID" type="int">
            <Comment>Determines what number to start iterating mover IDs.</Comment>
    </Parameter>
    <Parameter name="mineFieldWidth" type="double">
        <Comment>Width (X) of the field.</Comment>
    </Parameter>
    <Parameter name="mineFieldLength" type="double">
        <Comment>Length (Y) of the field.</Comment>
    </Parameter>    
    <Parameter name="mineFieldDepth" type="double">
        <Comment>Depth (Z) of the field.</Comment>
    </Parameter>
    <Parameter name="mineDistributionWidth" type="diskit.random.RandomVariateInstantiator">
        <Comment>RV that determines the distribution of mines over the width of the field.</Comment>
    </Parameter>
    <Parameter name="mineDistributionLength" type="diskit.random.RandomVariateInstantiator">
        <Comment>RV that determines the distribution of mines over the length of the field.</Comment>
    </Parameter>
    <Parameter name="mineDistributionDepth" type="diskit.random.RandomVariateInstantiator">
            <Comment>RV that determines the distribution of mines over the height of the field.</Comment>
    </Parameter>
    <StateVariable name="numberOfDetectionsByMine" type="int">
        <Comment>Number of unique detections.</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment/>
        <StateTransition state="numberOfDetectionsByMine">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="CreateMine" priority="0">
            <Comment/>
            <EdgeParameter value="firstMoverID"/>
        </Schedule>
        <Code>//System.out.println("Run event for Minefield:  ");</Code>
        <Coordinate x="70" y="50"/>
    </Event>
    <Event name="CreateMine">
        <Comment/>
        <Argument name="moverID" type="int"/>
        <LocalVariable name="movID" type="int" value="moverID">
            <Comment/>
        </LocalVariable>
        <LocalVariable name="x" type="double" value="mineDistributionWidth.generate()">
            <Comment/>
        </LocalVariable>
        <LocalVariable name="y" type="double" value="mineDistributionLength.generate()">
            <Comment/>
        </LocalVariable>
        <LocalVariable name="z" type="double" value="mineDistributionDepth.generate()">
            <Comment/>
        </LocalVariable>
        <Schedule condition="moverID &lt; (getFirstMoverID() + getNumberMines() - 1)" delay="0.0" event="CreateMine" priority="0">
            <Comment/>
            <EdgeParameter value="moverID + 1"/>
        </Schedule>
        <Schedule condition="true" delay="0.0" event="RegisterMine" priority="0">
            <Comment/>
            <EdgeParameter value="movID"/>
            <EdgeParameter value="mineLoc"/>
        </Schedule>
        <Code>diskit.Vec3d mineLoc = new diskit.Vec3d(x,y,z);

// System.out.println("MoverID is:" + moverID);</Code>
        <Coordinate x="70" y="140"/>
    </Event>
    <Event name="RegisterMine">
        <Comment/>
        <Argument name="moverIDnumber" type="int"/>
        <Argument name="mineLocation" type="diskit.Vec3d"/>
        <Schedule condition="true" delay="0.0" event="RegisterTarget" priority="0">
            <Comment/>
            <EdgeParameter value="mine"/>
        </Schedule>
        <Schedule condition="true" delay="0.0" event="RegisterSensor" priority="0">
            <Comment/>
            <EdgeParameter value="new diskit.SphereCutterSensor(mine, sensorRange)"/>
        </Schedule>
        <Code>diskit.DISMover3D mine = new diskit.DISMover3D(mineLocation, 0.0, moverIDnumber);

// System.out.println("Mineinfo is:" + mine.toString());

mine.setPersistant(false);</Code>
        <Coordinate x="70" y="260"/>
    </Event>
    <Event name="RegisterTarget">
        <Comment>Registers mine as a target.</Comment>
        <Argument name="mine" type="diskit.Mover3D"/>
        <Code/>
        <Coordinate x="170" y="230"/>
    </Event>
    <Event name="RegisterSensor">
        <Comment>Registers the mine's sensor with mediator.</Comment>
        <Argument name="sensorIn" type="diskit.Sensor">
            <Comment>Sensor of mine</Comment>
        </Argument>
        <LocalVariable name="sensor" type="diskit.Sensor" value="sensorIn">
            <Comment/>
        </LocalVariable>
        <Code>sensor.addSimEventListener(this);

sensor.setPersistant(false);</Code>
        <Coordinate x="170" y="310"/>
    </Event>
    <Event name="Detection">
        <Comment/>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Argument name="contact" type="diskit.Mover3D"/>
        <Schedule event="RegisterDetection"/>
        <Code>//System.out.println(sensor.getName() + " Detected: " + contact.getName());</Code>
        <Coordinate x="70" y="390"/>
    </Event>
    <Event name="RegisterDetection">
        <Comment/>
        <StateTransition state="numberOfDetectionsByMine">
            <Assignment value="numberOfDetectionsByMine + 1"/>
        </StateTransition>
        <Code>//System.out.println("test of test : " + getNumberOfMineDetections());</Code>
        <Coordinate x="160" y="390"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/SavageTactics/Sensors/ScenarioManagerWithSonars.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="Rick Goldberg" extend="diskit.ScenarioManager" name="ScenarioManagerWithSonars" package="test" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>used to initialize ScenarioManager with BasicLogRangeATLSonarMediator against any Mover3D</Comment>
    <Parameter name="speedScale" type="double">
        <Comment/>
    </Parameter>
    <Parameter name="clearOnReset" type="boolean">
        <Comment/>
    </Parameter>
    <Parameter name="inetAddr" type="java.lang.String">
        <Comment/>
    </Parameter>
    <Parameter name="port" type="int">
        <Comment/>
    </Parameter>
    <Parameter name="siteID" type="int">
        <Comment/>
    </Parameter>
    <Parameter name="appID" type="int">
        <Comment/>
    </Parameter>
    <Event name="Run">
        <Schedule condition="true" delay="0.0" event="AddSonarMediator" priority="0">
            <Comment/>
            <EdgeParameter value="diskit.MultiLRATLSonar.class"/>
            <EdgeParameter value="diskit.Mover3D.class"/>
            <EdgeParameter value="diskit.SonarMediator.class"/>
        </Schedule>
        <Code/>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="AddSonarMediator">
        <Comment/>
        <Argument name="sensor" type="java.lang.Class"/>
        <Argument name="target" type="java.lang.Class"/>
        <Argument name="mediator" type="java.lang.Class"/>
        <Code>addSensorTargetMediator(sensor,target,mediator);
addDefaultMediator(diskit.Mover3D.class); // taken out for perf test</Code>
        <Coordinate x="30" y="150"/>
    </Event>
    <Event name="AddDefaultMediator">
        <Comment>override this for perf test</Comment>
        <Argument name="target" type="java.lang.Class"/>
        <Code/>
        <Coordinate x="150" y="20"/>
    </Event>
</SimEntity>
