=== terry-norbraten/viskit/Schemas/simkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Event"/>
        <xs:element minOccurs="0" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="package" default="examples"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="author"/>
      <xs:attribute name="extend" default="SimEntityBase"/>
      <xs:attribute name="implement"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Comment" type="xs:string"/>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StateVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Event">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Argument"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LocalVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateTransition"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Schedule"/>
          <xs:element ref="Cancel"/>
        </xs:choice>
        <xs:element minOccurs="0" ref="Code"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Code" type="xs:string"/>
  <xs:element name="Argument">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocalVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="value"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Operation">
    <xs:complexType>
      <xs:attribute name="method" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Assignment">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <!-- bux fix 1183 -->
  <xs:element name="StateTransition">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="Assignment"/>
          <xs:element ref="Operation"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="state" use="required" type="xs:IDREF"/>
      <xs:attribute name="index"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EdgeParameter">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="delay" default="0.0"/>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="priority" default="DEFAULT">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="HIGHEST"/>
            <xs:enumeration value="HIGHER"/>
            <xs:enumeration value="HIGH"/>
            <xs:enumeration value="DEFAULT"/>
            <xs:enumeration value="LOW"/>
            <xs:enumeration value="LOWER"/>
            <xs:enumeration value="LOWEST"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cancel">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/BehaviorLibraries/examples/diskit/EventGraphs/Obstacles.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="SimEntityBase" name="Obstacles" package="diskit" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>Accepts as its argument an array of DISMover3D objects which represent both stationary and moving obstacles.  Normally the speed will be set to zero but the class uses DISMover3D to allow for obstacles that can move such as barriers and buoys.</Comment>
    <Parameter name="obstacles" type="DISMover3D[]">
        <Comment>Array of all obstacles for a port or scene.</Comment>
    </Parameter>
    <StateVariable name="numOfObstacles" type="int">
        <Comment>Index variable for creating obstacles sensors and targets</Comment>
    </StateVariable>
    <StateVariable name="obstacleSensorRange" type="double">
        <Comment>Can be any size, but should be variable if needed</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment/>
        <StateTransition state="numOfObstacles">
            <Assignment value="obstacles.length"/>
        </StateTransition>
        <StateTransition state="obstacleSensorRange">
            <Assignment value="20"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="RefereeRegister" priority="0">
            <Comment/>
            <EdgeParameter value="obstacles"/>
            <EdgeParameter value="numOfObstacles"/>
            <EdgeParameter value="obstacleSensorRange"/>
        </Schedule>
        <Code/>
        <Coordinate x="150" y="30"/>
    </Event>
    <Event name="CreateSensors">
        <Comment>Adds simple SphereCutterSensor to all obstacles.  A sensor is required as an argument for the doDetectionEvent of other entities</Comment>
        <Argument name="arraySize" type="int">
            <Comment>index variable for array construction</Comment>
        </Argument>
        <Argument name="targets" type="diskit.Mover3D[]">
            <Comment>Target array to pair targets and sensors</Comment>
        </Argument>
        <Argument name="sensorRange" type="double">
            <Comment>Fixed range for all sensors of obstacles</Comment>
        </Argument>
        <LocalVariable name="sensors" type="diskit.Sensor[]" value="new diskit.Sensor[arraySize]">
            <Comment>Array for sensors for each obstacle</Comment>
        </LocalVariable>
        <Schedule condition="true" delay="0.0" event="RegisterSensors" priority="0">
            <Comment/>
            <EdgeParameter value="sensors"/>
            <EdgeParameter value="targets"/>
        </Schedule>
        <Code>for(int i = 0; i &lt; arraySize; i++){     sensors[i] = new diskit.SphereCutterSensor(targets[i], sensorRange); }</Code>
        <Coordinate x="250" y="200"/>
    </Event>
    <Event name="CreateTargets">
        <Comment>Creates an array of DISMover3D objects for registering as targets</Comment>
        <Argument name="newObstacles" type="diskit.DISMover3D[]">
            <Comment>Passed from the constructor</Comment>
        </Argument>
        <Schedule condition="true" delay="0.0" event="RegisterTargets" priority="0">
            <Comment/>
            <EdgeParameter value="newObstacles"/>
        </Schedule>
        <Code/>
        <Coordinate x="260" y="90"/>
    </Event>
    <Event name="RegisterTargets">
        <Comment>Registers each DISMover3D in the array as it's own target</Comment>
        <Argument name="newTargets" type="diskit.Mover3D[]"/>
        <Code/>
        <Coordinate x="350" y="90"/>
    </Event>
    <Event name="RegisterSensors">
        <Comment>Registers each (sensor,target) pair of obstacles</Comment>
        <Argument name="newSensors" type="diskit.Sensor[]"/>
        <Argument name="movers" type="diskit.Mover3D[]">
            <Comment>Movers pass to register simEventListeners for each sensor</Comment>
        </Argument>
        <Code>for(int i = 0; i &lt; newSensors.length; i++){    newSensors[i].addSimEventListener(movers[i]); }</Code>
        <Coordinate x="350" y="200"/>
    </Event>
    <Event name="RefereeRegister">
        <Comment>Sends each mover one at a time and passes it to the Init event which is required for all entities</Comment>
        <Argument name="newMovers" type="diskit.Mover3D[]">
            <Comment>Array of movers to be registered</Comment>
        </Argument>
        <Argument name="numOfObst" type="int"/>
        <Argument name="range" type="double"/>
        <LocalVariable name="done" type="boolean" value="false">
            <Comment/>
        </LocalVariable>
        <LocalVariable name="idx" type="int" value="0">
            <Comment>variable for loop control</Comment>
        </LocalVariable>
        <LocalVariable name="arraySize" type="int" value="numOfObst">
            <Comment/>
        </LocalVariable>
        <Schedule condition="done" delay="0.0" event="CreateTargets" priority="0">
            <Comment>Check to make sure that that all movers are registered with the referee and then proceed</Comment>
            <EdgeParameter value="newMovers"/>
        </Schedule>
        <Schedule condition="done" delay="0.0" event="CreateSensors" priority="0">
            <Comment>Check to make sure all movers have been registered and then proceed</Comment>
            <EdgeParameter value="numOfObst"/>
            <EdgeParameter value="newMovers"/>
            <EdgeParameter value="range"/>
        </Schedule>
        <Schedule condition="!done" delay="0.0" event="RefereeRegister" priority="0">
            <Comment/>
            <EdgeParameter value="newMovers"/>
            <EdgeParameter value="numOfObst"/>
            <EdgeParameter value="range"/>
        </Schedule>
        <Schedule condition="true" delay="0.0" event="Init" priority="0">
            <Comment/>
            <EdgeParameter value="newMovers[idx]"/>
        </Schedule>
        <Code>if(idx &lt;  arraySize){    done = true; }else{  idx++; }</Code>
        <Coordinate x="150" y="140"/>
    </Event>
    <Event name="Init">
        <Comment>Registers each mover with the referee</Comment>
        <Argument name="thisMover" type="diskit.Mover3D"/>
        <Code/>
        <Coordinate x="40" y="140"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ServerWithReneges.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ServerWithReneges" package="examples" version="0.1.5" extend="SimEntityBase" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="numberServers" type="int"/>
    <Parameter name="serviceTime" type="simkit.random.RandomVariate"/>
    <Parameter name="renegeTime" type="simkit.random.RandomVariate"/>
    <StateVariable name="numberAvailableServers" type="int"/>
    <StateVariable name="queue" type="java.util.LinkedList&lt;Integer&gt;"/>
    <StateVariable name="numberServed" type="int"/>
    <StateVariable name="numberReneges" type="int">
        <Comment>this state variable stores the number of reneges</Comment>
        <Comment>as a Java int.</Comment>
    </StateVariable>
    <Event name="Run">
        <StateTransition state="numberAvailableServers">
            <Assignment value="getNumberServers()"/>
        </StateTransition>
        <StateTransition state="queue">
            <Operation method="clear()"/>
        </StateTransition>
        <StateTransition state="numberServed">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="numberReneges">
            <Assignment value="0"/>
        </StateTransition>
        <Coordinate x="35.0" y="15.0"/>
    </Event>
    <Event name="Arrival">
        <Argument name="customer" type="java.lang.Integer"/>
        <StateTransition state="queue">
            <Operation method="add(customer)"/>
        </StateTransition>
        <Schedule delay="renegeTime.generate()" event="Renege" priority="DEFAULT">
            <EdgeParameter value="customer"/>
        </Schedule>
        <Schedule delay="0.0" event="StartService" condition="getNumberAvailableServers() &gt; 0" priority="DEFAULT"/>
        <Coordinate x="25.0" y="105.0"/>
    </Event>
    <Event name="StartService">
        <LocalVariable name="customer" type="java.lang.Integer" value="queue.getFirst()">
            <Comment></Comment>
        </LocalVariable>
        <StateTransition state="queue">
            <Operation method="removeFirst()"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <Cancel event="Renege">
            <EdgeParameter value="customer"/>
        </Cancel>
        <Schedule delay="serviceTime.generate()" event="EndService" priority="DEFAULT">
            <EdgeParameter value="customer"/>
        </Schedule>
        <Coordinate x="175.0" y="105.0"/>
    </Event>
    <Event name="EndService">
        <Argument name="customer1" type="java.lang.Integer"/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers+1"/>
        </StateTransition>
        <StateTransition state="numberServed">
            <Assignment value="numberServed+1"/>
        </StateTransition>
        <Schedule event="StartService" condition="queue.size() &gt; 0" priority="HIGH"/>
        <Coordinate x="305.0" y="105.0"/>
    </Event>
    <Event name="Renege">
        <Argument name="customer2" type="java.lang.Integer"/>
        <StateTransition state="queue">
            <Operation method="remove(customer2)"/>
        </StateTransition>
        <StateTransition state="numberReneges">
            <Assignment value="numberReneges+1"/>
        </StateTransition>
        <Coordinate x="95.0" y="215.0"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/BasicExamples/Movers/ZoneMover.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="diskit.DISMover3D" name="ZoneMover" package="Movers" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="start" type="diskit.Vec3d">
        <Comment>The starting position for this entity</Comment>
    </Parameter>
    <Parameter name="maximumSpeed" type="double">
        <Comment>The maximum speed for this entity</Comment>
    </Parameter>
    <Parameter name="moverID" type="int">
        <Comment>The unique DIS entity ID number for this entity</Comment>
    </Parameter>
    <Parameter name="zones" type="diskit.ProbabilityZoneGeometry[]">
        <Comment>The zone geometry objects that will be used to generate waypoints</Comment>
    </Parameter>
    <StateVariable name="zoneMoverManager" type="diskit.ZoneMoverManager">
        <Comment>The mover manager that moves entities by using zone geometry</Comment>
    </StateVariable>
    <StateVariable name="waypointCreator" type="diskit.WaypointCreator">
        <Comment>Generates waypoints based on zones parameter</Comment>
    </StateVariable>
    <StateVariable name="tacticalMode" type="diskit.TacticalMode">
        <Comment>The mode that this mover is currently in</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment>Required event that is called at the begining of each simulation run</Comment>
        <StateTransition state="zoneMoverManager">
            <Assignment value="null"/>
        </StateTransition>
        <Schedule condition="zones.length &gt; 0" delay="0.0" event="ProcessZones" priority="0">
            <Comment>Only proceed if this mover has zones to process, otherwise do nothing</Comment>
        </Schedule>
        <Code/>
        <Coordinate x="20" y="150"/>
    </Event>
    <Event name="Init">
        <Comment>Called from super class to initialize movers</Comment>
        <Argument name="entity" type="simkit.SimEntity">
            <Comment>The entity being called by it's super class</Comment>
        </Argument>
        <Schedule condition="entity == this" delay="0.0" event="RegisterTarget" priority="0">
            <Comment>Only register this mover if the super class called this entity</Comment>
            <EdgeParameter value="this"/>
        </Schedule>
        <Code/>
        <Coordinate x="20" y="30"/>
    </Event>
    <Event name="RegisterTarget">
        <Comment>Registers this entity as a mover in the scenario</Comment>
        <Argument name="mover" type="diskit.Mover3D">
            <Comment>This mover</Comment>
        </Argument>
        <Code/>
        <Coordinate x="130" y="30"/>
    </Event>
    <Event name="ProcessZones">
        <Comment>This event creates waypoint creator and mover manager objects with the zones that were included as a parameter to this graph. If no zones are specificed the movement process will not be scheduled.</Comment>
        <StateTransition state="waypointCreator">
            <Assignment value="new diskit.WaypointCreator(zones)"/>
        </StateTransition>
        <StateTransition state="zoneMoverManager">
            <Assignment value="new diskit.ZoneMoverManager(this, waypointCreator)"/>
        </StateTransition>
        <Schedule event="StartMoving"/>
        <Code/>
        <Coordinate x="120" y="150"/>
    </Event>
    <Event name="StartMoving">
        <Comment>Begins the movement of this entity. Continuous movement based on waypoints from the provided zones will continue until the mover manager is changed</Comment>
        <LocalVariable name="initialLocation" type="diskit.Vec3d" value="waypointCreator.createWaypoint()">
            <Comment>An initial waypoint in one of the provided zones</Comment>
        </LocalVariable>
        <LocalVariable name="initialDestination" type="diskit.Vec3d" value="waypointCreator.createWaypoint()">
            <Comment>An initial destination in one of the zones</Comment>
        </LocalVariable>
        <StateTransition state="tacticalMode">
            <Assignment value="diskit.TacticalMode.TRANSITING"/>
        </StateTransition>
        <Code>/*REQUIRED CODE BLOCK FOR MOVER TO START MOVING
Without these method calls, IN THIS ORDER, the mover will do nothing. These method calls set the mover in motion and are invoking methods in the super class*/
setStartPosition(initialLocation);
setCruiseSpeed(maximumSpeed/2);
setDestination(initialDestination);
start();</Code>
        <Coordinate x="220" y="150"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/SavageTactics/Obstacles/Barrier.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="diskit.Obstacle" name="Barrier" package="Obstacles" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>A buoy which may be moving and effected by currents, wakes and tides.</Comment>
    <Parameter name="moverID" type="int">
        <Comment>Unique ID number for this object</Comment>
    </Parameter>
    <Parameter name="startPosition" type="diskit.Vec3d">
        <Comment>Center point of the barrier</Comment>
    </Parameter>
    <Parameter name="length" type="double">
        <Comment>length of the barrier</Comment>
    </Parameter>
    <Parameter name="width" type="double">
        <Comment>width of this pier</Comment>
    </Parameter>
    <Parameter name="height" type="double">
        <Comment>Height in meters above the waterline</Comment>
    </Parameter>
    <Parameter name="rotation" type="diskit.Vec4d">
        <Comment>Orientation in radians about the (Z DIS axis (Y for X3D)) example: 0 0 1 1.57</Comment>
    </Parameter>
    <StateVariable name="proximitySensor" type="diskit.Sensor">
        <Comment>Sensor used to detect when movers are getting close to the pier and should consider it for navigation</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment>Initializes all state variables for each simulation run.</Comment>
        <Code/>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="Init">
        <Comment>Used by diskit.ScenarioManager to register all entities</Comment>
        <Argument name="init" type="diskit.Mover3D"/>
        <StateTransition state="proximitySensor">
            <Assignment value="new diskit.SphereCutterSensor(this, getLength()/2)"/>
        </StateTransition>
        <Schedule condition="init == this" delay="0.0" event="RegisterSensor" priority="0.0">
            <Comment/>
            <EdgeParameter value="proximitySensor"/>
        </Schedule>
        <Schedule condition="init == this" delay="0.0" event="RegisterTarget" priority="0.0">
            <Comment/>
            <EdgeParameter value="this"/>
        </Schedule>
        <Code/>
        <Coordinate x="130" y="30"/>
    </Event>
    <Event name="RegisterSensor">
        <Comment>Passes Sensor to Relay for Registration</Comment>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Code/>
        <Coordinate x="250" y="110"/>
    </Event>
    <Event name="RegisterTarget">
        <Comment/>
        <Argument name="target" type="diskit.Mover3D"/>
        <Code/>
        <Coordinate x="250" y="30"/>
    </Event>
    <Event name="Detection">
        <Comment>Detects when a mover is getting close to this object</Comment>
        <Argument name="sensor" type="diskit.Sensor">
            <Comment>Sensor that detected the mover</Comment>
        </Argument>
        <Argument name="mover" type="diskit.Mover3D">
            <Comment>Mover that is getting close to obstacle</Comment>
        </Argument>
        <Schedule condition="true" delay="0.0" event="ObstacleClose" priority="0">
            <Comment/>
            <EdgeParameter value="mover"/>
            <EdgeParameter value="this"/>
        </Schedule>
        <Code/>
        <Coordinate x="150" y="210"/>
    </Event>
    <Event name="ObstacleClose">
        <Comment>Notification event that passes obstacle information to the detected mover. Also adds mover to the close contact queue.</Comment>
        <Argument name="mover" type="diskit.Mover3D">
            <Comment>Mover who is close to this object</Comment>
        </Argument>
        <Argument name="buoy" type="diskit.Obstacle">
            <Comment>Object that may need to be avoided</Comment>
        </Argument>
        <Code/>
        <Coordinate x="260" y="210"/>
    </Event>
    <Event name="BarrierAttacked">
        <Comment>Scheduled by an entity who attempts to explode this object</Comment>
        <Schedule event="BarrierDestroyed"/>
        <Code/>
        <Coordinate x="150" y="320"/>
    </Event>
    <Event name="BarrierDestroyed">
        <Comment>Occurs when the barrier is attacked</Comment>
        <LocalVariable name="hiddenLocation" type="diskit.Vec3d" value="new diskit.Vec3d(0, 1000, 0)">
            <Comment>If the barrier is destroyed move it below the sea level</Comment>
        </LocalVariable>
        <Code>setStartPosition(hiddenLocation);</Code>
        <Coordinate x="250" y="320"/>
    </Event>
    <Code/>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/SavageDefenseTactics/Communications/Communications.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="SimEntityBase" name="Communications" package="diskit" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="channel" type="int">
        <Comment/>
    </Parameter>
    <StateVariable name="message" type="String">
        <Comment/>
    </StateVariable>
    <Event name="Run">
        <Code/>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="CommsOrderIDContact">
        <Comment/>
        <Argument name="contact" type="diskit.Mover3D"/>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Argument name="originator" type="diskit.Mover3D"/>
        <Schedule condition="true" delay="0.0" event="IDContact" priority="0">
            <Comment/>
            <EdgeParameter value="contact"/>
            <EdgeParameter value="sensor"/>
        </Schedule>
        <Schedule condition="true" delay="0.0" event="DisplayComms" priority="0">
            <Comment/>
            <EdgeParameter value="contact"/>
            <EdgeParameter value="originator"/>
        </Schedule>
        <Code/>
        <Coordinate x="30" y="120"/>
    </Event>
    <Event name="IDContact">
        <Comment/>
        <Argument name="contact" type="diskit.Mover3D"/>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Code/>
        <Coordinate x="120" y="120"/>
    </Event>
    <Event name="DisplayComms">
        <Comment/>
        <Argument name="contact" type="diskit.DISMover3D"/>
        <Argument name="originator" type="diskit.DISMover3D"/>
        <Code>System.out.println("[Bridge to Bridge Radio CH: " + channel + "]    Patrol Craft, this is HVU# " + originator.getMoverID() + ", I have an unkown contact # " +contact.getMoverID() + " in the exclusion zone, Over.\n");</Code>
        <Coordinate x="30" y="210"/>
    </Event>
    <Event name="ClearExclusionZone">
        <Comment/>
        <Argument name="contact" type="diskit.Mover3D"/>
        <Argument name="sensor" type="diskit.Sensor"/>
        <Code/>
        <Coordinate x="30" y="320"/>
    </Event>
</SimEntity>
