=== terry-norbraten/viskit/Schemas/simkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="SimEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="head"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Event"/>
        <xs:element minOccurs="0" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="package" default="examples"/>
      <xs:attribute name="version" default="1.0"/>
      <xs:attribute name="author"/>
      <xs:attribute name="extend" default="SimEntityBase"/>
      <xs:attribute name="implement"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="head">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="meta"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="content"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Comment" type="xs:string"/>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StateVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Event">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Argument"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="LocalVariable"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="StateTransition"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Schedule"/>
          <xs:element ref="Cancel"/>
        </xs:choice>
        <xs:element minOccurs="0" ref="Code"/>
        <xs:element minOccurs="0" ref="Coordinate"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Code" type="xs:string"/>
  <xs:element name="Argument">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="LocalVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="value"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Coordinate">
    <xs:complexType>
      <xs:attribute name="x" use="required"/>
      <xs:attribute name="y" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Operation">
    <xs:complexType>
      <xs:attribute name="method" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Assignment">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <!-- bux fix 1183 -->
  <xs:element name="StateTransition">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="Assignment"/>
          <xs:element ref="Operation"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
      </xs:sequence>
      <xs:attribute name="state" use="required" type="xs:IDREF"/>
      <xs:attribute name="index"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EdgeParameter">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="delay" default="0.0"/>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="priority" default="DEFAULT">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="HIGHEST"/>
            <xs:enumeration value="HIGHER"/>
            <xs:enumeration value="HIGH"/>
            <xs:enumeration value="DEFAULT"/>
            <xs:enumeration value="LOW"/>
            <xs:enumeration value="LOWER"/>
            <xs:enumeration value="LOWEST"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cancel">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Code"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Comment"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="EdgeParameter"/>
      </xs:sequence>
      <xs:attribute name="event" use="required" type="xs:IDREF"/>
      <xs:attribute name="condition"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== terry-norbraten/viskit/BehaviorLibraries/examples/OA3302/TransferLineComponent.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity extend="SimEntityBase" name="TransferLineComponent" package="examples" version="0.0.2" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="totalNumberServers" type="int[]"/>
    <Parameter name="serviceTime" type="simkit.random.RandomVariate[]"/>
    <StateVariable name="numberAvailableServers" type="int[totalNumberServers.length]"/>
    <StateVariable name="numberInQueue" type="int[totalNumberServers.length]"/>
    <Event name="Run">
        <LocalVariable name="j" type="int" value="0">
            <Comment/>
        </LocalVariable>
        <LocalVariable name="_idxvar_0" type="int" value="0">
            <Comment>used internally</Comment>
        </LocalVariable>
        <LocalVariable name="_idxvar_1" type="int" value="0">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_0" state="numberAvailableServers">
            <Assignment value="totalNumberServers[_idxvar_0]"/>
        </StateTransition>
        <StateTransition index="_idxvar_1" state="numberInQueue">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule delay="0.0" event="InitializeWorkcenter">
            <EdgeParameter value="0"/>
        </Schedule>
        <Coordinate x="0" y="0"/>
    </Event>
    <Event name="InitializeWorkcenter">
        <Argument name="i" type="int"/>
        <LocalVariable name="_idxvar_26" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <LocalVariable name="_idxvar_27" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_26" state="numberInQueue">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition index="_idxvar_27" state="numberAvailableServers">
            <Assignment value="totalNumberServers[i]"/>
        </StateTransition>
        <Schedule condition="i &lt; totalNumberServers.length - 1" event="InitializeWorkcenter">
            <EdgeParameter value="i+1"/>
        </Schedule>
        <Coordinate x="120" y="0"/>
    </Event>
    <Event name="Arrival">
        <Argument name="i" type="int"/>
        <LocalVariable name="_idxvar_47" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_47" state="numberInQueue">
            <Assignment value="numberInQueue[i] + 1"/>
        </StateTransition>
        <Schedule condition="getNumberAvailableServers(i) &gt; 0" event="StartService">
            <EdgeParameter value="i"/>
        </Schedule>
        <Coordinate x="0" y="180"/>
    </Event>
    <Event name="StartService">
        <Argument name="i" type="int"/>
        <LocalVariable name="_idxvar_48" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <LocalVariable name="_idxvar_49" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_48" state="numberInQueue">
            <Assignment value="numberInQueue[i] + 1"/>
        </StateTransition>
        <StateTransition index="_idxvar_49" state="numberAvailableServers">
            <Assignment value="numberAvailableServers[i] - 1"/>
        </StateTransition>
        <Schedule delay="serviceTime[i].generate()" event="EndService">
            <EdgeParameter value="i"/>
        </Schedule>
        <Coordinate x="160" y="100"/>
    </Event>
    <Event name="EndService">
        <Argument name="i" type="int"/>
        <LocalVariable name="_idxvar_50" type="int" value="i">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_50" state="numberAvailableServers">
            <Assignment value="numberAvailableServers[i]+1"/>
        </StateTransition>
        <Schedule condition="getNumberInQueue(i) &gt; 0" event="StartService"/>
        <Schedule condition="i &lt; totalNumberServers.length - 1" event="Arrival"/>
        <Coordinate x="330" y="200"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/examples/diskit/SimServer3DTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="Rick Goldberg" package="examples.diskit" version="1.0" name="SimServer3DTest" extend="examples.diskit.DISServer3DBase" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>Simple test to count number of EntityStatePdu's received</Comment>
    <Parameter name="ipAddr" type="String">
        <Comment/>
    </Parameter>
    <Parameter name="port" type="int">
        <Comment/>
    </Parameter>    
    <Parameter type="double" name="msst"/>
    <StateVariable type="int" name="count">
        <Comment/>
    </StateVariable>
    <Event name="ESPDU_in">
        <Comment/>
        <Argument type="mil.navy.nps.dis.EntityStatePdu" name="pdu"/>
        <StateTransition state="count">
            <Assignment value="count+1"/>
        </StateTransition>
        <Coordinate x="220" y="160"/>
    </Event>
    <Event name="Run">
        <Comment/>
        <StateTransition state="count">
            <Assignment value="0"/>
        </StateTransition>
        <Coordinate x="80" y="170"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/BasicExamples/Movers/PathMover.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="diskit.DISMover3D" name="PathMover" package="Movers" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="start" type="diskit.Vec3d">
        <Comment>The starting position for this entity</Comment>
    </Parameter>
    <Parameter name="maximumSpeed" type="double">
        <Comment>The maximum speed for this entity</Comment>
    </Parameter>
    <Parameter name="moverID" type="int">
        <Comment>The unique DIS entity ID number for this entity</Comment>
    </Parameter>
    <Parameter name="waypoints" type="diskit.Vec3d[]">
        <Comment>The waypoints that this entity will use to navigate</Comment>
    </Parameter>
    <StateVariable name="pathMoverManager" type="diskit.PathMoverManager">
        <Comment>Provides the next waypoint based on the array of waypoints provided (in the order they were provided)</Comment>
    </StateVariable>
    <StateVariable name="tacticalMode" type="diskit.TacticalMode">
        <Comment>The mode that this mover is currently in</Comment>
    </StateVariable>
    <Event name="Run">
        <Comment>Required event that is called at the begining of each simulation run</Comment>
        <StateTransition state="pathMoverManager">
            <Assignment value="null"/>
        </StateTransition>
        <Schedule condition="waypoints.length &gt; 0" delay="0.0" event="ProcessWaypoints" priority="DEFAULT">
            <Comment>Only proceed if this mover has waypoints to process, otherwise do nothing</Comment>
        </Schedule>
        <Code/>
        <Coordinate x="20" y="150"/>
    </Event>
    <Event name="Init">
        <Comment>Called from super class to initialize movers</Comment>
        <Argument name="entity" type="simkit.SimEntity">
            <Comment>The entity being called by it's super class</Comment>
        </Argument>
        <Schedule condition="entity == this" delay="0.0" event="RegisterTarget" priority="DEFAULT">
            <Comment>Only register this mover if the super class called this entity</Comment>
            <EdgeParameter value="this"/>
        </Schedule>
        <Code/>
        <Coordinate x="20" y="30"/>
    </Event>
    <Event name="RegisterTarget">
        <Comment>Registers this entity as a mover in the scenario</Comment>
        <Argument name="mover" type="diskit.Mover3D">
            <Comment>This mover</Comment>
        </Argument>
        <Code/>
        <Coordinate x="130" y="30"/>
    </Event>
    <Event name="ProcessWaypoints">
        <Comment>This event creates a mover manager object with the waypoints that were included as a parameter to this graph. If no waypoints are specificed the movement process will not be scheduled.</Comment>
        <StateTransition state="pathMoverManager">
            <Assignment value="new diskit.PathMoverManager(this, waypoints, true)"/>
        </StateTransition>
        <Schedule event="StartMoving"/>
        <Code/>
        <Coordinate x="120" y="150"/>
    </Event>
    <Event name="StartMoving">
        <Comment>Begins the movement of this entity. Continuous movement based on waypoints from the provided zones will continue until the mover manager is changed</Comment>
        <StateTransition state="tacticalMode">
            <Assignment value="diskit.TacticalMode.TRANSITING"/>
        </StateTransition>
        <Code>/*REQUIRED CODE BLOCK FOR MOVER TO START MOVING
Without these method calls, IN THIS ORDER, the mover will do nothing. These method calls set the mover in motion and are invoking methods in the super class*/
setStartPosition(getLocation());
setCruiseSpeed(maximumSpeed/2);
start();</Code>
        <Coordinate x="220" y="150"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/viskit/test/ArrayTester.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="$author$" extend="SimEntityBase" name="ArrayTester" package="pkg" version="$id$" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <StateVariable name="sinus" type="double[180]">
        <Comment/>
    </StateVariable>
    <Event name="Run">
        <Comment/>
        <LocalVariable name="_idxvar_0" type="int" value="0">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_0" state="sinus">
            <Assignment value="Math.sin(2.0*Math.PI*((double)_idxvar_0)/((double)180))"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="DumpArrayElement" priority="0">
            <Comment/>
            <EdgeParameter value="0"/>
        </Schedule>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="DumpArrayElement">
        <Comment/>
        <Argument name="i" type="int"/>
        <LocalVariable name="code" type="boolean" value="true; System.out.println(getSinus(i))">
            <Comment/>
        </LocalVariable>
        <Schedule condition="i&lt;180" delay="0.0" event="DumpArrayElement" priority="0">
            <Comment/>
            <EdgeParameter value="i++"/>
        </Schedule>
        <Code>

System.out.println("Element "+i + " dumped. ");
if ( true ) {
	System.out.println("");
}

	</Code>
        <Coordinate x="200" y="110"/>
    </Event>
</SimEntity>

=== terry-norbraten/viskit/BehaviorLibraries/SavageTactics/Friendly/SurfaceSearchRadar.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity author="pjsulliv" extend="diskit.FriendlyForce" name="SurfaceSearchRadar" package="Friendly" version="1.0" xsi:noNamespaceSchemaLocation="http://diana.gl.nps.navy.mil/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>A civilian merchant ship. This behavior is set up for typical civilian merchant ship traffic. There is currenlty no difference between this graph and civilian merchant ship. It is a place holder for future developments</Comment>
    <Parameter name="moverID" type="int">
        <Comment>DIS entity ID</Comment>
    </Parameter>
    <Parameter name="entityDefinition" type="diskit.SMAL.EntityDefinition">
        <Comment>The Savage Modeling Analysis Language(SMAL) object that contains all specific information about the model being used</Comment>
    </Parameter>
    <Parameter name="radioCommunicationsChannel" type="int">
        <Comment>The radio channel that this entity uses to communicate</Comment>
    </Parameter>
    <Parameter name="radioCommunicationDelay" type="diskit.random.RandomVariateInstantiator">
        <Comment>The delay of a radio communication for this circuit</Comment>
    </Parameter>
    <Parameter name="surfaceRadar" type="diskit.Sensor">
        <Comment>The sensor range on this platform</Comment>
    </Parameter>
    <StateVariable name="radioCommunication" type="diskit.RadioCommunication">
        <Comment>An object used to transmit radio traffic</Comment>
    </StateVariable>
    <StateVariable name="nauticalChart" type="diskit.AStarZoneMap">
        <Comment>The AStar representation of the environment</Comment>
    </StateVariable>
    <StateVariable name="contactPicture" type="diskit.ContactPicture">
        <Comment>The contact picture for this entity</Comment>
    </StateVariable>
    <StateVariable name="radar" type="diskit.Sensor">
        <Comment/>
    </StateVariable>
    <Event name="Run">
        <Comment>The run event sets the parameter values for each simulation run</Comment>
        <Schedule condition="true" delay="0.0" event="Init" priority="0.0">
            <Comment/>
            <EdgeParameter value="this"/>
        </Schedule>
        <Code/>
        <Coordinate x="10" y="160"/>
    </Event>
    <Event name="Init">
        <Comment>An initialization event that is scheduled by diskit.SMALMover3D to initialize it's subclasses. The event creates sensor objects and registers this mover and it's sensors with the diskit.ScenarioManager.</Comment>
        <Argument name="init" type="diskit.Mover3D"/>
        <StateTransition state="radar">
            <Assignment value="surfaceRadar"/>
        </StateTransition>
        <StateTransition state="radar">
            <Operation method="setMover(this)"/>
        </StateTransition>
        <StateTransition state="radioCommunication">
            <Assignment value="new diskit.RadioCommunication(radioCommunicationsChannel,this)"/>
        </StateTransition>
        <StateTransition state="radioCommunication">
            <Operation method="setRecipients(friendlyForceList)"/>
        </StateTransition>
        <Schedule condition="init == this" delay="0.0" event="RegisterTarget" priority="0.0">
            <Comment/>
            <EdgeParameter value="this"/>
        </Schedule>
        <Schedule condition="init == this" delay="0.0" event="RegisterSensor" priority="0.0">
            <EdgeParameter value="surfaceRadar"/>
        </Schedule>
        <Code>System.out.println("***Init");</Code>
        <Coordinate x="10" y="10"/>
    </Event>
    <Event name="RegisterTarget">
        <Comment>Registers this mover with the diskit.ScenarioManager</Comment>
        <Argument name="mover" type="diskit.Mover3D">
            <Comment>This object should pass itself as an argument to this event as part of the registration process</Comment>
        </Argument>
        <Code/>
        <Coordinate x="100" y="10"/>
    </Event>
    <Event name="RegisterSensor">
        <Comment/>
        <Argument name="sensor" type="diskit.Sensor">
            <Comment>The sensor for this entity</Comment>
        </Argument>
        <Code>System.out.println("***Sensors registered");</Code>
        <Coordinate x="100" y="80"/>
    </Event>
    <Event name="PrepareRadioMessage">
        <Comment>Prepares a radio message for transmitting</Comment>
        <Argument name="msgText" type="java.lang.String">
            <Comment>The text of the message</Comment>
        </Argument>
        <Argument name="msgType" type="java.lang.String">
            <Comment>The type of message being sent</Comment>
        </Argument>
        <Argument name="msgContext" type="diskit.Mover3D">
            <Comment>The context of the message</Comment>
        </Argument>
        <StateTransition state="radioCommunication">
            <Operation method="setMessage(msgText)"/>
        </StateTransition>
        <StateTransition state="radioCommunication">
            <Operation method="setType(msgType)"/>
        </StateTransition>
        <StateTransition state="radioCommunication">
            <Operation method="setContext(msgContext)"/>
        </StateTransition>
        <Schedule condition="true" delay="java.lang.Math.max(0.0,radioCommunicationDelay.generate())" event="SendRadioMessage" priority="0.0">
            <Comment/>
            <EdgeParameter value="radioCommunication"/>
        </Schedule>
        <Code/>
        <Coordinate x="170" y="360"/>
    </Event>
    <Event name="SendRadioMessage">
        <Comment>Transmits the radio message via the scenario manager.  Since this entity sends messages to different types of movers the recipient of the message is reset after transmission to ensure that the default is set</Comment>
        <Argument name="msg" type="diskit.RadioCommunication">
            <Comment>The message to transmit</Comment>
        </Argument>
        <Code/>
        <Coordinate x="300" y="360"/>
    </Event>
    <Event name="Detection">
        <Comment>Marks the detection event for this mover's sensor object</Comment>
        <Argument name="sensor" type="diskit.Sensor">
            <Comment>The sensor that detected the contact</Comment>
        </Argument>
        <Argument name="contact" type="diskit.Mover3D">
            <Comment>The mover that was detected</Comment>
        </Argument>
        <LocalVariable name="isFriendlyForce" type="boolean" value="friendlyForces.contains(contact.getMoverID())">
            <Comment>Returns true if this contact is a friendly force</Comment>
        </LocalVariable>
        <LocalVariable name="entityType" type="java.lang.String" value="contact.getEntityType()">
            <Comment>Returns this entities type</Comment>
        </LocalVariable>
        <Schedule condition="!isFriendlyForce &amp;&amp; !contactPicture.contains(contact)" delay="0.0" event="UnknownContact" priority="0">
            <Comment/>
            <EdgeParameter value="contact"/>
        </Schedule>
        <Code>System.out.println("*** Radar got detection");
System.out.println("harbor map: " + nauticalChart);</Code>
        <Coordinate x="30" y="360"/>
    </Event>
    <Event name="UnknownContact">
        <Comment>If there is an unknown contact this entity will attempt to contact it and warn all other friendly entities</Comment>
        <Argument name="contact" type="diskit.Mover3D">
            <Comment>The mover that is in question</Comment>
        </Argument>
        <LocalVariable name="contactArea" type="diskit.AStarZoneGeometry" value="nauticalChart.findClosestZone(contact.getLocation())">
            <Comment>Returns the zone closest to the contact</Comment>
        </LocalVariable>
        <LocalVariable name="contactLocation" type="java.lang.String" value="contactArea.getName()">
            <Comment>Returns the general area of the contact</Comment>
        </LocalVariable>
        <LocalVariable name="query" type="java.lang.String" value="&quot;Unknown contact in the vicinity of &quot; + contactLocation + &quot;, this is &quot; + getName() +&quot;. You are in restricted waters. Request you identify yourself, over.&quot;">
            <Comment>The query text for this entity</Comment>
        </LocalVariable>
        <LocalVariable name="warningText" type="java.lang.String" value="&quot;All stations, there is an inbound contact in the vicinity of &quot; + contactLocation">
            <Comment>message text for warning other entities</Comment>
        </LocalVariable>
        <StateTransition state="contactPicture">
            <Operation method="add(contact)"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="PrepareRadioMessage" priority="0">
            <Comment/>
            <EdgeParameter value="warningText"/>
            <EdgeParameter value="&quot;WarningReport&quot;"/>
            <EdgeParameter value="contact"/>
        </Schedule>
        <Code/>
        <Coordinate x="90" y="460"/>
    </Event>
    <Event name="AStarZoneMapDistributed">
        <Comment>Receives a copy of the AStarZoneMap from the ScenarioManager</Comment>
        <Argument name="recipient" type="simkit.SimEntity"/>
        <Argument name="harborChart" type="diskit.AStarZoneMap"/>
        <StateTransition state="nauticalChart">
            <Assignment value="harborChart"/>
        </StateTransition>
        <Code>System.out.println("Got map: " + harborChart);</Code>
        <Coordinate x="200" y="30"/>
    </Event>
</SimEntity>
